// This file is auto-generated by @hey-api/openapi-ts

export const AddressFamilySchema = {
    type: 'integer'
} as const;

export const AlgorithmSchema = {
    type: 'integer'
} as const;

export const ArticleCreateModelSchema = {
    required: [
        'title',
        'content'
    ],
    type: 'object',
    properties: {
        title: {
            maxLength: 200,
            type: 'string'
        },
        content: {
            maxLength: 10000,
            type: 'string'
        },
        coverUrl: {
            maxLength: 500,
            type: [
                'null',
                'string'
            ]
        },
        isPublished: {
            type: 'boolean'
        }
    }
} as const;

export const ArticleResponseSchema = {
    type: 'object',
    properties: {
        id: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        title: {
            type: 'string'
        },
        content: {
            type: 'string'
        },
        authorId: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        authorUsername: {
            type: [
                'null',
                'string'
            ]
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        },
        isPublished: {
            type: 'boolean'
        },
        coverUrl: {
            type: [
                'null',
                'string'
            ]
        },
        commentCount: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        }
    }
} as const;

export const ArticleUpdateModelSchema = {
    required: [
        'title',
        'content'
    ],
    type: 'object',
    properties: {
        title: {
            maxLength: 200,
            type: 'string'
        },
        content: {
            type: 'string'
        },
        coverUrl: {
            maxLength: 500,
            type: [
                'null',
                'string'
            ]
        },
        isPublished: {
            type: 'boolean'
        }
    }
} as const;

export const AsnEncodedDataSchema = {
    type: 'object',
    properties: {
        oid: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/Oid'
                }
            ]
        },
        rawData: {
            type: 'string',
            format: 'byte'
        }
    }
} as const;

export const AssertionOptionsSchema = {
    type: 'object',
    properties: {
        challenge: {
            format: 'byte'
        },
        timeout: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'uint64'
        },
        rpId: {
            type: [
                'null',
                'string'
            ]
        },
        allowCredentials: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PublicKeyCredentialDescriptor'
            }
        },
        userVerification: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/UserVerificationRequirement'
                }
            ]
        },
        hints: {
            type: 'array'
        },
        extensions: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/AuthenticationExtensionsClientInputs'
                }
            ]
        }
    }
} as const;

export const AssertionResponseSchema = {
    required: [
        'authenticatorData',
        'signature',
        'clientDataJSON'
    ],
    type: 'object',
    properties: {
        authenticatorData: {
            format: 'byte'
        },
        signature: {
            format: 'byte'
        },
        clientDataJSON: {
            format: 'byte'
        },
        userHandle: {
            format: 'byte'
        }
    }
} as const;

export const AsymmetricAlgorithmSchema = {
    type: 'object',
    properties: {
        keySize: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        legalKeySizes: {
            type: [
                'null',
                'array'
            ],
            items: {
                $ref: '#/components/schemas/KeySizes'
            }
        },
        signatureAlgorithm: {
            type: [
                'null',
                'string'
            ]
        },
        keyExchangeAlgorithm: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const AttestationConveyancePreferenceSchema = {} as const;

export const AttestationResponseSchema = {
    required: [
        'attestationObject',
        'clientDataJSON',
        'transports'
    ],
    type: 'object',
    properties: {
        attestationObject: {
            format: 'byte'
        },
        clientDataJSON: {
            format: 'byte'
        },
        transports: {
            type: [
                'null',
                'array'
            ]
        }
    }
} as const;

export const AuthenticationExtensionsClientInputsSchema = {
    type: 'object',
    properties: {
        'example.extension.bool': {
            type: [
                'null',
                'boolean'
            ]
        },
        exts: {
            type: [
                'null',
                'boolean'
            ]
        },
        uvm: {
            type: [
                'null',
                'boolean'
            ]
        },
        credProps: {
            type: [
                'null',
                'boolean'
            ]
        },
        prf: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/AuthenticationExtensionsPRFInputs'
                }
            ]
        },
        largeBlob: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/AuthenticationExtensionsLargeBlobInputs'
                }
            ]
        },
        credentialProtectionPolicy: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/CredentialProtectionPolicy'
                }
            ]
        },
        enforceCredentialProtectionPolicy: {
            type: [
                'null',
                'boolean'
            ]
        }
    }
} as const;

export const AuthenticationExtensionsClientOutputsSchema = {
    type: 'object',
    properties: {
        'example.extension.bool': {
            type: [
                'null',
                'boolean'
            ]
        },
        appid: {
            type: 'boolean'
        },
        exts: {
            type: [
                'null',
                'array'
            ],
            items: {
                type: 'string'
            }
        },
        uvm: {
            type: [
                'null',
                'array'
            ],
            items: {
                type: 'array',
                items: {
                    pattern: '^-?(?:0|[1-9]\\d*)$',
                    type: [
                        'integer',
                        'string'
                    ],
                    format: 'uint64'
                }
            }
        },
        credProps: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/CredentialPropertiesOutput'
                }
            ]
        },
        prf: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/AuthenticationExtensionsPRFOutputs'
                }
            ]
        },
        largeBlob: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/AuthenticationExtensionsLargeBlobOutputs'
                }
            ]
        },
        credProtect: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/CredentialProtectionPolicy'
                }
            ]
        }
    }
} as const;

export const AuthenticationExtensionsLargeBlobInputsSchema = {
    type: 'object',
    properties: {
        support: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/LargeBlobSupport'
                }
            ]
        },
        read: {
            type: 'boolean'
        },
        write: {
            format: 'byte'
        }
    }
} as const;

export const AuthenticationExtensionsLargeBlobOutputsSchema = {
    type: 'object',
    properties: {
        supported: {
            type: 'boolean'
        },
        blob: {
            format: 'byte'
        },
        written: {
            type: 'boolean'
        }
    }
} as const;

export const AuthenticationExtensionsPRFInputsSchema = {
    type: 'object',
    properties: {
        eval: {
            $ref: '#/components/schemas/AuthenticationExtensionsPRFValues'
        },
        evalByCredential: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/KeyValuePairOfstringAndAuthenticationExtensionsPRFValues'
                }
            ]
        }
    }
} as const;

export const AuthenticationExtensionsPRFOutputsSchema = {
    type: 'object',
    properties: {
        enabled: {
            type: 'boolean'
        },
        results: {
            $ref: '#/components/schemas/AuthenticationExtensionsPRFValues'
        }
    }
} as const;

export const AuthenticationExtensionsPRFValuesSchema = {
    required: [
        'first'
    ],
    type: 'object',
    properties: {
        first: {
            format: 'byte'
        },
        second: {
            format: 'byte'
        }
    }
} as const;

export const AuthenticatorAssertionRawResponseSchema = {
    required: [
        'id',
        'rawId',
        'type',
        'clientExtensionResults'
    ],
    type: 'object',
    properties: {
        id: {
            type: [
                'null',
                'string'
            ]
        },
        rawId: {
            format: 'byte'
        },
        response: {
            $ref: '#/components/schemas/AssertionResponse'
        },
        type: {
            $ref: '#/components/schemas/PublicKeyCredentialType'
        },
        extensions: {
            $ref: '#/components/schemas/AuthenticationExtensionsClientOutputs'
        },
        clientExtensionResults: {
            $ref: '#/components/schemas/AuthenticationExtensionsClientOutputs'
        }
    }
} as const;

export const AuthenticatorAttachmentSchema = {} as const;

export const AuthenticatorAttestationRawResponseSchema = {
    required: [
        'id',
        'rawId',
        'type',
        'response',
        'clientExtensionResults'
    ],
    type: 'object',
    properties: {
        id: {
            type: [
                'null',
                'string'
            ]
        },
        rawId: {
            format: 'byte'
        },
        type: {
            $ref: '#/components/schemas/PublicKeyCredentialType'
        },
        response: {
            $ref: '#/components/schemas/AttestationResponse'
        },
        extensions: {
            $ref: '#/components/schemas/AuthenticationExtensionsClientOutputs'
        },
        clientExtensionResults: {
            $ref: '#/components/schemas/AuthenticationExtensionsClientOutputs'
        }
    }
} as const;

export const AuthenticatorSelectionSchema = {
    type: 'object',
    properties: {
        authenticatorAttachment: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/AuthenticatorAttachment'
                }
            ]
        },
        residentKey: {
            $ref: '#/components/schemas/ResidentKeyRequirement'
        },
        requireResidentKey: {
            type: 'boolean'
        },
        userVerification: {
            $ref: '#/components/schemas/UserVerificationRequirement'
        }
    }
} as const;

export const AuthLoginModelSchema = {
    required: [
        'email',
        'password'
    ],
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        captchaToken: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const AuthRegisterModelSchema = {
    required: [
        'username',
        'email',
        'password'
    ],
    type: 'object',
    properties: {
        username: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        inviteCode: {
            type: [
                'null',
                'string'
            ]
        },
        captchaToken: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const AuthResponseSchema = {
    type: 'object',
    properties: {
        status: {
            type: 'string'
        },
        data: {
            $ref: '#/components/schemas/TokenRenewResponse'
        }
    }
} as const;

export const BatchDeleteResponseSchema = {
    type: 'object',
    properties: {
        deletedKeys: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        failedKeys: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const BucketResponseSchema = {
    required: [
        'name'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        creationDate: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const BucketStatusResponseSchema = {
    required: [
        'bucketName'
    ],
    type: 'object',
    properties: {
        bucketName: {
            type: 'string'
        },
        region: {
            type: [
                'null',
                'string'
            ]
        },
        objectCount: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        totalSizeBytes: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int64'
        },
        isAccessible: {
            type: 'boolean'
        },
        errorMessage: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const CancellationTokenSchema = {
    type: 'object',
    properties: {
        isCancellationRequested: {
            type: 'boolean'
        },
        canBeCanceled: {
            type: 'boolean'
        },
        waitHandle: {
            $ref: '#/components/schemas/WaitHandle'
        }
    }
} as const;

export const ClaimSchema = {
    type: 'object',
    properties: {
        issuer: {
            type: [
                'null',
                'string'
            ]
        },
        originalIssuer: {
            type: [
                'null',
                'string'
            ]
        },
        properties: {
            type: [
                'null',
                'object'
            ],
            additionalProperties: {
                type: 'string'
            }
        },
        subject: {
            $ref: '#/components/schemas/ClaimsIdentity'
        },
        type: {
            type: [
                'null',
                'string'
            ]
        },
        value: {
            type: [
                'null',
                'string'
            ]
        },
        valueType: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const ClaimsIdentitySchema = {
    type: 'object',
    properties: {
        authenticationType: {
            type: [
                'null',
                'string'
            ]
        },
        isAuthenticated: {
            type: 'boolean'
        },
        actor: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/ClaimsIdentity'
                }
            ]
        },
        bootstrapContext: {},
        claims: {},
        label: {
            type: [
                'null',
                'string'
            ]
        },
        name: {
            type: [
                'null',
                'string'
            ]
        },
        nameClaimType: {
            type: [
                'null',
                'string'
            ]
        },
        roleClaimType: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const ClaimsPrincipalSchema = {
    type: 'object',
    properties: {
        claims: {
            type: [
                'null',
                'array'
            ],
            items: {
                $ref: '#/components/schemas/Claim'
            }
        },
        identities: {
            type: [
                'null',
                'array'
            ],
            items: {
                $ref: '#/components/schemas/ClaimsIdentity'
            }
        },
        identity: {
            $ref: '#/components/schemas/IIdentity'
        }
    }
} as const;

export const CommentCreateModelSchema = {
    required: [
        'content'
    ],
    type: 'object',
    properties: {
        content: {
            maxLength: 2000,
            type: 'string'
        },
        parentCommentId: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'null',
                'integer',
                'string'
            ],
            format: 'int32'
        }
    }
} as const;

export const CommentResponseSchema = {
    type: 'object',
    properties: {
        id: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        content: {
            type: 'string'
        },
        articleId: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        authorId: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        authorUsername: {
            type: [
                'null',
                'string'
            ]
        },
        parentCommentId: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'null',
                'integer',
                'string'
            ],
            format: 'int32'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        },
        isDeleted: {
            type: 'boolean'
        },
        replyCount: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        }
    }
} as const;

export const CommentUpdateModelSchema = {
    required: [
        'content'
    ],
    type: 'object',
    properties: {
        content: {
            maxLength: 2000,
            type: 'string'
        }
    }
} as const;

export const ConnectionInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        remoteIpAddress: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/IPAddress'
                }
            ]
        },
        remotePort: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        localIpAddress: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/IPAddress'
                }
            ]
        },
        localPort: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        clientCertificate: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/X509Certificate2'
                }
            ]
        }
    }
} as const;

export const CopyFileRequestSchema = {
    required: [
        'sourceKey',
        'destinationKey'
    ],
    type: 'object',
    properties: {
        sourceKey: {
            type: 'string'
        },
        destinationKey: {
            type: 'string'
        }
    }
} as const;

export const CreateAppRequestSchema = {
    required: [
        'displayName',
        'redirectUris'
    ],
    type: 'object',
    properties: {
        displayName: {
            type: 'string'
        },
        redirectUris: {
            type: [
                'null',
                'array'
            ],
            items: {
                type: 'string'
            }
        },
        clientType: {
            type: [
                'null',
                'string'
            ],
            default: 'confidential'
        },
        applicationType: {
            type: [
                'null',
                'string'
            ],
            default: 'web'
        }
    }
} as const;

export const CreateAppResponseSchema = {
    required: [
        'id',
        'clientId',
        'clientSecret',
        'displayName'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        clientId: {
            type: 'string'
        },
        clientSecret: {
            type: 'string'
        },
        displayName: {
            type: 'string'
        }
    }
} as const;

export const CreateInvitationRequestSchema = {
    required: [
        'uses',
        'hoursValid'
    ],
    type: 'object',
    properties: {
        uses: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        hoursValid: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        }
    }
} as const;

export const CreateStickerSetRequestSchema = {
    required: [
        'name'
    ],
    type: 'object',
    properties: {
        name: {
            maxLength: 100,
            type: 'string'
        }
    }
} as const;

export const CredentialCreateOptionsSchema = {
    required: [
        'rp',
        'user',
        'challenge',
        'pubKeyCredParams'
    ],
    type: 'object',
    properties: {
        rp: {
            $ref: '#/components/schemas/PublicKeyCredentialRpEntity'
        },
        user: {
            $ref: '#/components/schemas/Fido2User'
        },
        challenge: {
            format: 'byte'
        },
        pubKeyCredParams: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PubKeyCredParam'
            }
        },
        timeout: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'uint64'
        },
        attestation: {
            $ref: '#/components/schemas/AttestationConveyancePreference'
        },
        attestationFormats: {
            type: 'array'
        },
        authenticatorSelection: {
            $ref: '#/components/schemas/AuthenticatorSelection'
        },
        hints: {
            type: 'array'
        },
        excludeCredentials: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PublicKeyCredentialDescriptor'
            }
        },
        extensions: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/AuthenticationExtensionsClientInputs'
                }
            ]
        }
    }
} as const;

export const CredentialPropertiesOutputSchema = {
    type: 'object',
    properties: {
        rk: {
            type: 'boolean'
        },
        authenticatorDisplayName: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const CredentialProtectionPolicySchema = {} as const;

export const CredentialUpdateModelSchema = {
    type: 'object',
    properties: {
        nickname: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const Fido2UserSchema = {
    type: 'object',
    properties: {
        name: {
            type: [
                'null',
                'string'
            ]
        },
        id: {
            format: 'byte'
        },
        displayName: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const FileShareCreateRequestSchema = {
    required: [
        'bucket',
        'key',
        'fileName'
    ],
    type: 'object',
    properties: {
        bucket: {
            type: 'string'
        },
        key: {
            type: 'string'
        },
        fileName: {
            type: 'string'
        },
        remarks: {
            type: [
                'null',
                'string'
            ]
        },
        isPublic: {
            type: 'boolean'
        },
        expiresAt: {
            type: [
                'null',
                'string'
            ],
            format: 'date-time'
        }
    }
} as const;

export const FileShareListResponseSchema = {
    required: [
        'items'
    ],
    type: 'object',
    properties: {
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/FileShareResponse'
            }
        },
        totalCount: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        page: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        pageSize: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        }
    }
} as const;

export const FileShareResponseSchema = {
    required: [
        'shortId',
        'bucket',
        'key',
        'fileName'
    ],
    type: 'object',
    properties: {
        shortId: {
            type: 'string'
        },
        bucket: {
            type: 'string'
        },
        key: {
            type: 'string'
        },
        fileName: {
            type: 'string'
        },
        remarks: {
            type: [
                'null',
                'string'
            ]
        },
        isPublic: {
            type: 'boolean'
        },
        isEnabled: {
            type: 'boolean'
        },
        ownerId: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        expiresAt: {
            type: [
                'null',
                'string'
            ],
            format: 'date-time'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const FileShareUpdateRequestSchema = {
    type: 'object',
    properties: {
        key: {
            type: [
                'null',
                'string'
            ]
        },
        bucket: {
            type: [
                'null',
                'string'
            ]
        },
        remarks: {
            type: [
                'null',
                'string'
            ]
        },
        isEnabled: {
            type: [
                'null',
                'boolean'
            ]
        },
        isPublic: {
            type: [
                'null',
                'boolean'
            ]
        },
        expiresAt: {
            type: [
                'null',
                'string'
            ],
            format: 'date-time'
        },
        fileName: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const FooterBeianSettingsSchema = {
    required: [
        'icp',
        'police'
    ],
    type: 'object',
    properties: {
        icp: {
            type: 'string'
        },
        police: {
            type: 'string'
        }
    }
} as const;

export const FooterSettingsSchema = {
    required: [
        'beian'
    ],
    type: 'object',
    properties: {
        beian: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/FooterBeianSettings'
                }
            ]
        }
    }
} as const;

export const HomeBackgroundSettingsSchema = {
    required: [
        'url',
        'blur',
        'opacity'
    ],
    type: 'object',
    properties: {
        url: {
            type: 'string'
        },
        blur: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        opacity: {
            pattern: '^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?(?:[eE][+-]?\\d+)?$',
            type: [
                'number',
                'string'
            ],
            format: 'double'
        }
    }
} as const;

export const HomeBannerSettingsSchema = {
    required: [
        'content',
        'displayMode'
    ],
    type: 'object',
    properties: {
        content: {
            type: 'string'
        },
        displayMode: {
            type: 'string'
        }
    }
} as const;

export const HostStringSchema = {
    type: 'object',
    properties: {
        value: {
            type: [
                'null',
                'string'
            ]
        },
        hasValue: {
            type: 'boolean'
        },
        host: {
            type: [
                'null',
                'string'
            ]
        },
        port: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'null',
                'integer',
                'string'
            ],
            format: 'int32'
        }
    }
} as const;

export const HttpContextSchema = {
    type: 'object',
    properties: {
        features: {
            type: [
                'null',
                'array'
            ],
            items: {
                $ref: '#/components/schemas/KeyValuePairOfTypeAndObject'
            }
        },
        request: {
            $ref: '#/components/schemas/HttpRequest'
        },
        response: {
            $ref: '#/components/schemas/HttpResponse'
        },
        connection: {
            $ref: '#/components/schemas/ConnectionInfo'
        },
        webSockets: {
            $ref: '#/components/schemas/WebSocketManager'
        },
        user: {
            $ref: '#/components/schemas/ClaimsPrincipal'
        },
        items: {
            type: 'object'
        },
        requestServices: {
            $ref: '#/components/schemas/IServiceProvider'
        },
        requestAborted: {
            $ref: '#/components/schemas/CancellationToken'
        },
        traceIdentifier: {
            type: 'string'
        },
        session: {
            $ref: '#/components/schemas/ISession'
        }
    }
} as const;

export const HttpRequestSchema = {
    type: 'object',
    properties: {
        httpContext: {
            $ref: '#/components/schemas/HttpContext'
        },
        method: {
            type: 'string'
        },
        scheme: {
            type: 'string'
        },
        isHttps: {
            type: 'boolean'
        },
        host: {
            $ref: '#/components/schemas/HostString'
        },
        pathBase: {
            $ref: '#/components/schemas/PathString'
        },
        path: {
            $ref: '#/components/schemas/PathString'
        },
        queryString: {
            $ref: '#/components/schemas/QueryString'
        },
        query: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/KeyValuePairOfstringAndStringValues'
            }
        },
        protocol: {
            type: 'string'
        },
        headers: {
            type: [
                'null',
                'object'
            ],
            additionalProperties: {
                type: 'array',
                items: {
                    type: 'string'
                }
            }
        },
        cookies: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/KeyValuePairOfstringAndstring'
            }
        },
        contentLength: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'null',
                'integer',
                'string'
            ],
            format: 'int64'
        },
        contentType: {
            type: [
                'null',
                'string'
            ]
        },
        body: {
            $ref: '#/components/schemas/Stream'
        },
        bodyReader: {
            $ref: '#/components/schemas/PipeReader'
        },
        hasFormContentType: {
            type: 'boolean'
        },
        form: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/KeyValuePairOfstringAndStringValues'
            }
        },
        routeValues: {
            type: 'object'
        }
    }
} as const;

export const HttpResponseSchema = {
    type: 'object',
    properties: {
        httpContext: {
            $ref: '#/components/schemas/HttpContext'
        },
        statusCode: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        headers: {
            type: [
                'null',
                'object'
            ],
            additionalProperties: {
                type: 'array',
                items: {
                    type: 'string'
                }
            }
        },
        body: {
            $ref: '#/components/schemas/Stream'
        },
        bodyWriter: {
            $ref: '#/components/schemas/PipeWriter'
        },
        contentLength: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'null',
                'integer',
                'string'
            ],
            format: 'int64'
        },
        contentType: {
            type: [
                'null',
                'string'
            ]
        },
        cookies: {
            $ref: '#/components/schemas/IResponseCookies'
        },
        hasStarted: {
            type: 'boolean'
        }
    }
} as const;

export const IFormFileSchema = {
    type: 'string',
    format: 'binary'
} as const;

export const IIdentitySchema = {
    type: 'object',
    properties: {
        name: {
            type: [
                'null',
                'string'
            ]
        },
        authenticationType: {
            type: [
                'null',
                'string'
            ]
        },
        isAuthenticated: {
            type: 'boolean'
        }
    }
} as const;

export const InviteSchema = {
    type: 'object',
    properties: {
        id: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        code: {
            type: 'string'
        },
        creatorId: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        expireAt: {
            type: [
                'null',
                'string'
            ],
            format: 'date-time'
        },
        maxUses: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        usedCount: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        isDisabled: {
            type: 'boolean'
        },
        creator: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/User'
                }
            ]
        },
        usedBy: {
            type: [
                'null',
                'array'
            ],
            items: {
                $ref: '#/components/schemas/User'
            }
        },
        isValid: {
            type: 'boolean'
        }
    }
} as const;

export const IPAddressSchema = {
    type: 'object',
    properties: {
        addressFamily: {
            $ref: '#/components/schemas/AddressFamily'
        },
        scopeId: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int64'
        },
        isIPv6Multicast: {
            type: 'boolean'
        },
        isIPv6LinkLocal: {
            type: 'boolean'
        },
        isIPv6SiteLocal: {
            type: 'boolean'
        },
        isIPv6Teredo: {
            type: 'boolean'
        },
        isIPv6UniqueLocal: {
            type: 'boolean'
        },
        isIPv4MappedToIPv6: {
            type: 'boolean'
        },
        address: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int64'
        }
    }
} as const;

export const IResponseCookiesSchema = {
    type: 'object'
} as const;

export const IServiceProviderSchema = {
    type: 'object'
} as const;

export const ISessionSchema = {
    type: 'object',
    properties: {
        isAvailable: {
            type: 'boolean'
        },
        id: {
            type: [
                'null',
                'string'
            ]
        },
        keys: {
            type: [
                'null',
                'array'
            ],
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const JsonElementSchema = {} as const;

export const KeySizesSchema = {
    required: [
        'minSize',
        'maxSize',
        'skipSize'
    ],
    type: 'object',
    properties: {
        minSize: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        maxSize: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        skipSize: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        }
    }
} as const;

export const KeyValuePairOfstringAndAuthenticationExtensionsPRFValuesSchema = {
    required: [
        'key',
        'value'
    ],
    type: 'object',
    properties: {
        key: {
            type: [
                'null',
                'string'
            ]
        },
        value: {
            $ref: '#/components/schemas/AuthenticationExtensionsPRFValues'
        }
    }
} as const;

export const KeyValuePairOfstringAndstringSchema = {
    required: [
        'key',
        'value'
    ],
    type: 'object',
    properties: {
        key: {
            type: [
                'null',
                'string'
            ]
        },
        value: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const KeyValuePairOfstringAndStringValuesSchema = {
    required: [
        'key',
        'value'
    ],
    type: 'object',
    properties: {
        key: {
            type: [
                'null',
                'string'
            ]
        },
        value: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const KeyValuePairOfTypeAndObjectSchema = {
    required: [
        'key',
        'value'
    ],
    type: 'object',
    properties: {
        key: {
            $ref: '#/components/schemas/Type'
        },
        value: {}
    }
} as const;

export const LargeBlobSupportSchema = {} as const;

export const MessageResponseSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string'
        }
    }
} as const;

export const NewSecretResponseSchema = {
    required: [
        'clientSecret'
    ],
    type: 'object',
    properties: {
        clientSecret: {
            type: 'string'
        }
    }
} as const;

export const OAuth2ApproveRequestSchema = {
    required: [
        'clientId',
        'redirectUri'
    ],
    type: 'object',
    properties: {
        clientId: {
            type: 'string'
        },
        redirectUri: {
            type: 'string'
        },
        scope: {
            type: [
                'null',
                'string'
            ]
        },
        approved: {
            type: 'boolean'
        },
        state: {
            type: [
                'null',
                'string'
            ]
        },
        codeChallenge: {
            type: [
                'null',
                'string'
            ]
        },
        codeChallengeMethod: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const OAuth2ApproveResultResponseSchema = {
    type: 'object',
    properties: {
        success: {
            type: 'boolean'
        },
        redirectUrl: {
            type: [
                'null',
                'string'
            ]
        },
        error: {
            type: [
                'null',
                'string'
            ]
        },
        errorDescription: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const OAuth2AuthorizeResponseSchema = {
    type: 'object',
    properties: {
        clientId: {
            type: 'string'
        },
        appName: {
            type: 'string'
        },
        description: {
            type: [
                'null',
                'string'
            ]
        },
        homepage: {
            type: [
                'null',
                'string'
            ]
        },
        redirectUri: {
            type: 'string'
        },
        scopes: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        scopeDescriptions: {
            type: 'object',
            additionalProperties: {
                type: 'string'
            }
        },
        state: {
            type: [
                'null',
                'string'
            ]
        },
        userId: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        appCreator: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const OAuth2ErrorResponseSchema = {
    type: 'object',
    properties: {
        error: {
            type: 'string'
        },
        errorDescription: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const OAuth2TokenResponseSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string'
        },
        tokenType: {
            type: 'string'
        },
        expiresIn: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        refreshToken: {
            type: [
                'null',
                'string'
            ]
        },
        scope: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const OAuthAppDetailResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        clientId: {
            type: 'string'
        },
        displayName: {
            type: 'string'
        },
        userId: {
            type: [
                'null',
                'string'
            ]
        },
        redirectUris: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        clientType: {
            type: 'string'
        },
        applicationType: {
            type: 'string'
        },
        consentType: {
            type: 'string'
        }
    }
} as const;

export const OAuthAppResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        clientId: {
            type: 'string'
        },
        displayName: {
            type: 'string'
        },
        userId: {
            type: [
                'null',
                'string'
            ]
        },
        clientType: {
            type: 'string'
        },
        applicationType: {
            type: 'string'
        },
        consentType: {
            type: 'string'
        }
    }
} as const;

export const OAuthConsentResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        applicationId: {
            type: 'string'
        },
        clientId: {
            type: 'string'
        },
        displayName: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const OAuthTokenResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        applicationId: {
            type: 'string'
        },
        clientId: {
            type: 'string'
        },
        displayName: {
            type: 'string'
        },
        tokenType: {
            type: 'string'
        },
        expiresAt: {
            type: 'string',
            format: 'date-time'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const OidSchema = {
    type: 'object',
    properties: {
        value: {
            type: [
                'null',
                'string'
            ]
        },
        friendlyName: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const PatchAppRequestSchema = {
    type: 'object',
    properties: {
        displayName: {
            type: [
                'null',
                'string'
            ]
        },
        redirectUris: {
            type: [
                'null',
                'array'
            ],
            items: {
                type: 'string'
            }
        },
        clientType: {
            type: [
                'null',
                'string'
            ]
        },
        applicationType: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const PathStringSchema = {
    type: 'object',
    properties: {
        value: {
            type: [
                'null',
                'string'
            ]
        },
        hasValue: {
            type: 'boolean'
        }
    }
} as const;

export const PipeReaderSchema = {
    type: [
        'null',
        'string'
    ],
    format: 'binary'
} as const;

export const PipeWriterSchema = {
    type: 'object',
    properties: {
        canGetUnflushedBytes: {
            type: 'boolean'
        },
        unflushedBytes: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int64'
        }
    }
} as const;

export const PresignedUrlResponseSchema = {
    required: [
        'url',
        'key'
    ],
    type: 'object',
    properties: {
        url: {
            type: 'string'
        },
        key: {
            type: 'string'
        },
        expiresAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const PresignUploadRequestSchema = {
    required: [
        'key'
    ],
    type: 'object',
    properties: {
        key: {
            type: 'string'
        },
        contentType: {
            type: [
                'null',
                'string'
            ]
        },
        expirationMinutes: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'null',
                'integer',
                'string'
            ],
            format: 'int32'
        }
    }
} as const;

export const ProblemDetailsSchema = {
    type: 'object',
    properties: {
        type: {
            type: [
                'null',
                'string'
            ]
        },
        title: {
            type: [
                'null',
                'string'
            ]
        },
        status: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'null',
                'integer',
                'string'
            ],
            format: 'int32'
        },
        detail: {
            type: [
                'null',
                'string'
            ]
        },
        instance: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const PubKeyCredParamSchema = {
    required: [
        'alg'
    ],
    type: 'object',
    properties: {
        type: {
            default: 'public-key'
        },
        alg: {
            $ref: '#/components/schemas/Algorithm'
        }
    }
} as const;

export const PublicKeySchema = {
    type: 'object',
    properties: {
        encodedKeyValue: {
            $ref: '#/components/schemas/AsnEncodedData'
        },
        encodedParameters: {
            $ref: '#/components/schemas/AsnEncodedData'
        },
        key: {
            $ref: '#/components/schemas/AsymmetricAlgorithm'
        },
        oid: {
            $ref: '#/components/schemas/Oid'
        }
    }
} as const;

export const PublicKeyCredentialDescriptorSchema = {
    required: [
        'type',
        'id'
    ],
    type: 'object',
    properties: {
        type: {
            $ref: '#/components/schemas/PublicKeyCredentialType'
        },
        id: {
            format: 'byte'
        },
        transports: {
            type: [
                'null',
                'array'
            ]
        }
    }
} as const;

export const PublicKeyCredentialRpEntitySchema = {
    required: [
        'id',
        'name'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        icon: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const PublicKeyCredentialTypeSchema = {} as const;

export const QueryStringSchema = {
    type: 'object',
    properties: {
        value: {
            type: [
                'null',
                'string'
            ]
        },
        hasValue: {
            type: 'boolean'
        }
    }
} as const;

export const ReadOnlyMemoryOfbyteSchema = {
    type: 'string'
} as const;

export const ResidentKeyRequirementSchema = {} as const;

export const S3ObjectMetadataResponseSchema = {
    required: [
        'key'
    ],
    type: 'object',
    properties: {
        key: {
            type: 'string'
        },
        contentType: {
            type: [
                'null',
                'string'
            ]
        },
        contentLength: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int64'
        },
        lastModified: {
            type: 'string',
            format: 'date-time'
        },
        eTag: {
            type: [
                'null',
                'string'
            ]
        },
        metadata: {
            type: 'object',
            additionalProperties: {
                type: 'string'
            }
        }
    }
} as const;

export const S3ObjectResponseSchema = {
    required: [
        'key'
    ],
    type: 'object',
    properties: {
        key: {
            type: 'string'
        },
        size: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int64'
        },
        lastModified: {
            type: 'string',
            format: 'date-time'
        },
        eTag: {
            type: [
                'null',
                'string'
            ]
        },
        storageClass: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const SafeWaitHandleSchema = {
    type: 'object',
    properties: {
        isInvalid: {
            type: 'boolean'
        },
        isClosed: {
            type: 'boolean'
        }
    }
} as const;

export const SeoGeneralSettingsSchema = {
    required: [
        'title',
        'description',
        'keywords',
        'robots'
    ],
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        keywords: {
            type: 'string'
        },
        robots: {
            type: 'string'
        }
    }
} as const;

export const SettingListItemSchema = {
    type: 'object',
    properties: {
        key: {
            type: 'string'
        },
        type: {
            type: 'string'
        },
        defaultValue: {},
        currentValue: {}
    }
} as const;

export const ShortcodeCreateModelSchema = {
    required: [
        'name',
        'displayName',
        'frontendCode',
        'backendCode'
    ],
    type: 'object',
    properties: {
        name: {
            maxLength: 100,
            type: 'string'
        },
        displayName: {
            maxLength: 200,
            type: 'string'
        },
        description: {
            maxLength: 1000,
            type: [
                'null',
                'string'
            ]
        },
        frontendCode: {
            type: 'string'
        },
        backendCode: {
            type: 'string'
        },
        permission: {
            $ref: '#/components/schemas/ShortcodePermission'
        },
        allowedRoles: {
            type: [
                'null',
                'array'
            ],
            items: {
                type: 'string'
            }
        },
        isEnabled: {
            type: 'boolean'
        }
    }
} as const;

export const ShortcodeDetailSchema = {
    type: 'object',
    properties: {
        id: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        name: {
            type: 'string'
        },
        displayName: {
            type: 'string'
        },
        description: {
            type: [
                'null',
                'string'
            ]
        },
        frontendCode: {
            type: 'string'
        },
        backendCode: {
            type: 'string'
        },
        permission: {
            $ref: '#/components/schemas/ShortcodePermission'
        },
        allowedRoles: {
            type: [
                'null',
                'array'
            ],
            items: {
                type: 'string'
            }
        },
        isEnabled: {
            type: 'boolean'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        },
        createdByUserId: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        createdByUsername: {
            type: 'string'
        }
    }
} as const;

export const ShortcodeErrorSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'string'
        },
        message: {
            type: 'string'
        },
        details: {}
    }
} as const;

export const ShortcodeExecutionResultSchema = {
    type: 'object',
    properties: {
        success: {
            type: 'boolean'
        },
        data: {},
        error: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/ShortcodeError'
                }
            ]
        }
    }
} as const;

export const ShortcodeListItemSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        displayName: {
            type: 'string'
        },
        description: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const ShortcodeListResponseSchema = {
    type: 'object',
    properties: {
        shortcodes: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ShortcodeListItem'
            }
        }
    }
} as const;

export const ShortcodePermissionSchema = {
    type: 'integer'
} as const;

export const ShortcodeStatusModelSchema = {
    required: [
        'isEnabled'
    ],
    type: 'object',
    properties: {
        isEnabled: {
            type: 'boolean'
        }
    }
} as const;

export const ShortcodeUpdateModelSchema = {
    type: 'object',
    properties: {
        displayName: {
            maxLength: 200,
            type: [
                'null',
                'string'
            ]
        },
        description: {
            maxLength: 1000,
            type: [
                'null',
                'string'
            ]
        },
        frontendCode: {
            type: [
                'null',
                'string'
            ]
        },
        backendCode: {
            type: [
                'null',
                'string'
            ]
        },
        permission: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/ShortcodePermission'
                }
            ]
        },
        allowedRoles: {
            type: [
                'null',
                'array'
            ],
            items: {
                type: 'string'
            }
        },
        isEnabled: {
            type: [
                'null',
                'boolean'
            ]
        }
    }
} as const;

export const StickerImageUrlResponseSchema = {
    type: 'object',
    properties: {
        url: {
            type: 'string'
        }
    }
} as const;

export const StickerResponseSchema = {
    required: [
        'id',
        'name'
    ],
    type: 'object',
    properties: {
        id: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const StickerSetDetailResponseSchema = {
    required: [
        'id',
        'name',
        'stickers'
    ],
    type: 'object',
    properties: {
        id: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        name: {
            type: 'string'
        },
        stickers: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/StickerResponse'
            }
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const StickerSetResponseSchema = {
    required: [
        'id',
        'name'
    ],
    type: 'object',
    properties: {
        id: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        name: {
            type: 'string'
        },
        stickerCount: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const StickerUploadItemSchema = {
    required: [
        'name'
    ],
    type: 'object',
    properties: {
        name: {
            maxLength: 100,
            type: 'string'
        },
        contentType: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const StorageStatusResponseSchema = {
    type: 'object',
    properties: {
        isConnected: {
            type: 'boolean'
        },
        bucketCount: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        ownerId: {
            type: [
                'null',
                'string'
            ]
        },
        ownerDisplayName: {
            type: [
                'null',
                'string'
            ]
        },
        errorMessage: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const StreamSchema = {
    type: 'string',
    format: 'binary'
} as const;

export const TokenRenewResponseSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string'
        },
        user: {
            $ref: '#/components/schemas/User'
        },
        expires: {
            type: [
                'null',
                'string'
            ],
            format: 'date-time'
        }
    }
} as const;

export const TotpSetupResponseSchema = {
    type: 'object',
    properties: {
        secret: {
            type: 'string'
        },
        url: {
            type: 'string'
        }
    }
} as const;

export const TotpVerifyRequestSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'string'
        }
    }
} as const;

export const TwoFactorPolicyResponseSchema = {
    type: 'object',
    properties: {
        totp: {
            $ref: '#/components/schemas/TwoFactorStatus'
        },
        forceTwoFactor: {
            type: 'boolean'
        }
    }
} as const;

export const TwoFactorStatusSchema = {
    type: 'object',
    properties: {
        enabled: {
            type: 'boolean'
        }
    }
} as const;

export const TypeSchema = {} as const;

export const UpdateAppRequestSchema = {
    required: [
        'displayName',
        'redirectUris'
    ],
    type: 'object',
    properties: {
        displayName: {
            type: 'string'
        },
        redirectUris: {
            type: [
                'null',
                'array'
            ],
            items: {
                type: 'string'
            }
        },
        clientType: {
            type: [
                'null',
                'string'
            ]
        },
        applicationType: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const UpdateInvitationRequestSchema = {
    required: [
        'isDisabled',
        'uses',
        'hoursValid'
    ],
    type: 'object',
    properties: {
        isDisabled: {
            type: [
                'null',
                'boolean'
            ]
        },
        uses: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'null',
                'integer',
                'string'
            ],
            format: 'int32'
        },
        hoursValid: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'null',
                'integer',
                'string'
            ],
            format: 'int32'
        }
    }
} as const;

export const UpdateProfileModelSchema = {
    type: 'object',
    properties: {
        newPassword: {
            type: [
                'null',
                'string'
            ]
        },
        username: {
            type: [
                'null',
                'string'
            ]
        },
        oldPassword: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const UpdateSettingBodySchema = {
    type: 'object',
    properties: {
        value: {
            $ref: '#/components/schemas/JsonElement'
        }
    }
} as const;

export const UpdateStickerSetRequestSchema = {
    type: 'object',
    properties: {
        name: {
            maxLength: 100,
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const UpdateUserStatusBodySchema = {
    type: 'object',
    properties: {
        isBanned: {
            type: 'boolean'
        }
    }
} as const;

export const UploadedStickerResponseSchema = {
    required: [
        'id',
        'name',
        'key',
        'uploadUrl'
    ],
    type: 'object',
    properties: {
        id: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        name: {
            type: 'string'
        },
        key: {
            type: 'string'
        },
        uploadUrl: {
            type: 'string'
        },
        expiresAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const UploadStickersRequestSchema = {
    required: [
        'items'
    ],
    type: 'object',
    properties: {
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/StickerUploadItem'
            }
        }
    }
} as const;

export const UrlResponseSchema = {
    type: 'object',
    properties: {
        url: {
            type: 'string'
        }
    }
} as const;

export const UserSchema = {
    type: 'object',
    properties: {
        id: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        username: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        role: {
            $ref: '#/components/schemas/UserRole'
        },
        isBanned: {
            type: 'boolean'
        },
        registerTime: {
            type: 'string',
            format: 'date-time'
        },
        avatar: {
            type: 'string'
        },
        usedInviteId: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'null',
                'integer',
                'string'
            ],
            format: 'int32'
        }
    }
} as const;

export const UserCredentialSchema = {
    type: 'object',
    properties: {
        id: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        credentialId: {
            type: 'string',
            format: 'byte'
        },
        publicKey: {
            type: 'string',
            format: 'byte'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        signatureCounter: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'uint32'
        },
        nickname: {
            type: 'string'
        },
        userId: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        }
    }
} as const;

export const UserRoleSchema = {
    type: 'integer'
} as const;

export const UserVerificationRequirementSchema = {} as const;

export const WaitHandleSchema = {
    type: 'object',
    properties: {
        handle: {},
        safeWaitHandle: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/SafeWaitHandle'
                }
            ]
        }
    }
} as const;

export const WebSocketManagerSchema = {
    type: 'object',
    properties: {
        isWebSocketRequest: {
            type: 'boolean'
        },
        webSocketRequestedProtocols: {
            type: [
                'null',
                'array'
            ],
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const X500DistinguishedNameSchema = {
    type: 'object',
    properties: {
        name: {
            type: [
                'null',
                'string'
            ]
        },
        oid: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/Oid'
                }
            ]
        },
        rawData: {
            type: 'string',
            format: 'byte'
        }
    }
} as const;

export const X509Certificate2Schema = {
    type: 'object',
    properties: {
        archived: {
            type: 'boolean'
        },
        extensions: {
            type: [
                'null',
                'array'
            ],
            items: {
                $ref: '#/components/schemas/X509Extension'
            }
        },
        friendlyName: {
            type: 'string'
        },
        hasPrivateKey: {
            type: 'boolean'
        },
        privateKey: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/AsymmetricAlgorithm'
                }
            ]
        },
        issuerName: {
            $ref: '#/components/schemas/X500DistinguishedName'
        },
        notAfter: {
            type: 'string',
            format: 'date-time'
        },
        notBefore: {
            type: 'string',
            format: 'date-time'
        },
        publicKey: {
            $ref: '#/components/schemas/PublicKey'
        },
        rawData: {
            type: [
                'null',
                'string'
            ],
            format: 'byte'
        },
        rawDataMemory: {
            $ref: '#/components/schemas/ReadOnlyMemoryOfbyte'
        },
        serialNumber: {
            type: [
                'null',
                'string'
            ]
        },
        signatureAlgorithm: {
            $ref: '#/components/schemas/Oid'
        },
        subjectName: {
            $ref: '#/components/schemas/X500DistinguishedName'
        },
        thumbprint: {
            type: [
                'null',
                'string'
            ]
        },
        version: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        handle: {},
        issuer: {
            type: [
                'null',
                'string'
            ]
        },
        subject: {
            type: [
                'null',
                'string'
            ]
        },
        serialNumberBytes: {
            $ref: '#/components/schemas/ReadOnlyMemoryOfbyte'
        }
    }
} as const;

export const X509ExtensionSchema = {
    type: 'object',
    properties: {
        critical: {
            type: 'boolean'
        },
        oid: {
            oneOf: [
                {
                    type: 'null'
                },
                {
                    $ref: '#/components/schemas/Oid'
                }
            ]
        },
        rawData: {
            type: 'string',
            format: 'byte'
        }
    }
} as const;
