// This file is auto-generated by @hey-api/openapi-ts

export const AuthLoginModelSchema = {
    required: [
        'email',
        'password'
    ],
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        captchaToken: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;
