// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { GetUserProfileData, GetUserProfileResponses, PostAuthLoginData, PostAuthLoginResponses, PostAuthRenewData, PostAuthRenewResponses, PostUserAvatarData, PostUserAvatarResponses, PostUserProfileData, PostUserProfileResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>) => (options.client ?? client).post<PostAuthLoginResponses, unknown, ThrowOnError>({
    url: '/Auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postAuthRenew = <ThrowOnError extends boolean = false>(options?: Options<PostAuthRenewData, ThrowOnError>) => (options?.client ?? client).post<PostAuthRenewResponses, unknown, ThrowOnError>({ url: '/Auth/renew', ...options });

export const getUserProfile = <ThrowOnError extends boolean = false>(options?: Options<GetUserProfileData, ThrowOnError>) => (options?.client ?? client).get<GetUserProfileResponses, unknown, ThrowOnError>({ url: '/User/profile', ...options });

export const postUserProfile = <ThrowOnError extends boolean = false>(options: Options<PostUserProfileData, ThrowOnError>) => (options.client ?? client).post<PostUserProfileResponses, unknown, ThrowOnError>({
    url: '/User/profile',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postUserAvatar = <ThrowOnError extends boolean = false>(options: Options<PostUserAvatarData, ThrowOnError>) => (options.client ?? client).post<PostUserAvatarResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/User/avatar',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});
