// This file is auto-generated by @hey-api/openapi-ts

import type { GetUserProfileResponse, PostAuthLoginResponse, PostAuthRenewResponse } from './types.gen';

const userTableSchemaResponseTransformer = (data: any) => {
    if (data.registerTime) {
        data.registerTime = new Date(data.registerTime);
    }
    return data;
};

const authResponseSchemaResponseTransformer = (data: any) => {
    if (data.user) {
        data.user = userTableSchemaResponseTransformer(data.user);
    }
    if (data.expires) {
        data.expires = new Date(data.expires);
    }
    return data;
};

export const postAuthLoginResponseTransformer = async (data: any): Promise<PostAuthLoginResponse> => {
    data = authResponseSchemaResponseTransformer(data);
    return data;
};

export const postAuthRenewResponseTransformer = async (data: any): Promise<PostAuthRenewResponse> => {
    data = authResponseSchemaResponseTransformer(data);
    return data;
};

export const getUserProfileResponseTransformer = async (data: any): Promise<GetUserProfileResponse> => {
    data = userTableSchemaResponseTransformer(data);
    return data;
};
