// This file is auto-generated by @hey-api/openapi-ts

import type { GetAdminCommentsPendingResponse, GetAdminCommentsResponse, GetAdminFileSharesByShortIdResponse, GetAdminFileSharesResponse, GetAdminInvitationsByIdResponse, GetAdminInvitationsByIdUsersResponse, GetAdminInvitationsResponse, GetAdminShortcodesByIdResponse, GetAdminShortcodesResponse, GetAdminStickerSetsByIdResponse, GetAdminStickerSetsResponse, GetAdminStorageBucketByBucketNameFileResponse, GetAdminStorageBucketByBucketNameFilesResponse, GetAdminStorageBucketByBucketNamePresignDownloadResponse, GetAdminStorageBucketsResponse, GetAdminUsersResponse, GetArticlesByIdResponse, GetArticlesResponse, GetAuthWebauthnCredentialsResponse, GetCommentsArticleByArticleIdResponse, GetCommentsByCommentIdRepliesResponse, GetSettingsGeneralInfoResponse, GetStickerSetsByIdResponse, GetStickerSetsResponse, GetUserOauthAuthorizationsResponse, GetUserOauthTokensResponse, GetUserProfileResponse, PatchAdminFileSharesByShortIdResponse, PatchAdminShortcodesByIdStatusResponse, PostAdminFileSharesResponse, PostAdminInvitationsResponse, PostAdminShortcodesResponse, PostAdminStickerSetsByIdStickersResponse, PostAdminStickerSetsResponse, PostAdminStorageBucketByBucketNamePresignUploadResponse, PostArticlesResponse, PostAuthLoginResponse, PostAuthRegisterResponse, PostAuthRenewResponse, PostCommentsResponse, PutAdminShortcodesByIdResponse, PutAdminStickerSetsByIdResponse, PutAdminStickerSetsByIdStickersByStickerIdResponse, PutArticlesByIdResponse, PutCommentsByIdResponse } from './types.gen';

const articleResponseSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const getArticlesResponseTransformer = async (data: any): Promise<GetArticlesResponse> => {
    data = data.map((item: any) => articleResponseSchemaResponseTransformer(item));
    return data;
};

export const postArticlesResponseTransformer = async (data: any): Promise<PostArticlesResponse> => {
    data = articleResponseSchemaResponseTransformer(data);
    return data;
};

export const getArticlesByIdResponseTransformer = async (data: any): Promise<GetArticlesByIdResponse> => {
    data = articleResponseSchemaResponseTransformer(data);
    return data;
};

export const putArticlesByIdResponseTransformer = async (data: any): Promise<PutArticlesByIdResponse> => {
    data = articleResponseSchemaResponseTransformer(data);
    return data;
};

const userSchemaResponseTransformer = (data: any) => {
    if (data.registerTime) {
        data.registerTime = new Date(data.registerTime);
    }
    return data;
};

const tokenRenewResponseSchemaResponseTransformer = (data: any) => {
    if (data.user) {
        data.user = userSchemaResponseTransformer(data.user);
    }
    if (data.expires) {
        data.expires = new Date(data.expires);
    }
    return data;
};

const authResponseSchemaResponseTransformer = (data: any) => {
    if (data.data) {
        data.data = tokenRenewResponseSchemaResponseTransformer(data.data);
    }
    return data;
};

export const postAuthLoginResponseTransformer = async (data: any): Promise<PostAuthLoginResponse> => {
    data = authResponseSchemaResponseTransformer(data);
    return data;
};

export const postAuthRegisterResponseTransformer = async (data: any): Promise<PostAuthRegisterResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

export const postAuthRenewResponseTransformer = async (data: any): Promise<PostAuthRenewResponse> => {
    data = tokenRenewResponseSchemaResponseTransformer(data);
    return data;
};

const commentResponseSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const getCommentsArticleByArticleIdResponseTransformer = async (data: any): Promise<GetCommentsArticleByArticleIdResponse> => {
    data = data.map((item: any) => commentResponseSchemaResponseTransformer(item));
    return data;
};

export const getCommentsByCommentIdRepliesResponseTransformer = async (data: any): Promise<GetCommentsByCommentIdRepliesResponse> => {
    data = data.map((item: any) => commentResponseSchemaResponseTransformer(item));
    return data;
};

export const postCommentsResponseTransformer = async (data: any): Promise<PostCommentsResponse> => {
    data = commentResponseSchemaResponseTransformer(data);
    return data;
};

export const putCommentsByIdResponseTransformer = async (data: any): Promise<PutCommentsByIdResponse> => {
    data = commentResponseSchemaResponseTransformer(data);
    return data;
};

const generalInfoSettingsSchemaResponseTransformer = (data: any) => {
    data.siteCreatedAt = new Date(data.siteCreatedAt);
    return data;
};

export const getSettingsGeneralInfoResponseTransformer = async (data: any): Promise<GetSettingsGeneralInfoResponse> => {
    data = generalInfoSettingsSchemaResponseTransformer(data);
    return data;
};

const stickerSetResponseSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const getStickerSetsResponseTransformer = async (data: any): Promise<GetStickerSetsResponse> => {
    data = data.map((item: any) => stickerSetResponseSchemaResponseTransformer(item));
    return data;
};

const stickerSetDetailResponseSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const getStickerSetsByIdResponseTransformer = async (data: any): Promise<GetStickerSetsByIdResponse> => {
    data = stickerSetDetailResponseSchemaResponseTransformer(data);
    return data;
};

export const getUserProfileResponseTransformer = async (data: any): Promise<GetUserProfileResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

const oAuthConsentResponseSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    return data;
};

export const getUserOauthAuthorizationsResponseTransformer = async (data: any): Promise<GetUserOauthAuthorizationsResponse> => {
    data = data.map((item: any) => oAuthConsentResponseSchemaResponseTransformer(item));
    return data;
};

const oAuthTokenResponseSchemaResponseTransformer = (data: any) => {
    if (data.expiresAt) {
        data.expiresAt = new Date(data.expiresAt);
    }
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    return data;
};

export const getUserOauthTokensResponseTransformer = async (data: any): Promise<GetUserOauthTokensResponse> => {
    data = data.map((item: any) => oAuthTokenResponseSchemaResponseTransformer(item));
    return data;
};

const userCredentialSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    return data;
};

export const getAuthWebauthnCredentialsResponseTransformer = async (data: any): Promise<GetAuthWebauthnCredentialsResponse> => {
    data = data.map((item: any) => userCredentialSchemaResponseTransformer(item));
    return data;
};

const adminCommentResponseSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const getAdminCommentsResponseTransformer = async (data: any): Promise<GetAdminCommentsResponse> => {
    data = data.map((item: any) => adminCommentResponseSchemaResponseTransformer(item));
    return data;
};

export const getAdminCommentsPendingResponseTransformer = async (data: any): Promise<GetAdminCommentsPendingResponse> => {
    data = data.map((item: any) => adminCommentResponseSchemaResponseTransformer(item));
    return data;
};

const fileShareResponseSchemaResponseTransformer = (data: any) => {
    if (data.expiresAt) {
        data.expiresAt = new Date(data.expiresAt);
    }
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    return data;
};

const fileShareListResponseSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => fileShareResponseSchemaResponseTransformer(item));
    return data;
};

export const getAdminFileSharesResponseTransformer = async (data: any): Promise<GetAdminFileSharesResponse> => {
    data = fileShareListResponseSchemaResponseTransformer(data);
    return data;
};

export const postAdminFileSharesResponseTransformer = async (data: any): Promise<PostAdminFileSharesResponse> => {
    data = fileShareResponseSchemaResponseTransformer(data);
    return data;
};

export const getAdminFileSharesByShortIdResponseTransformer = async (data: any): Promise<GetAdminFileSharesByShortIdResponse> => {
    data = fileShareResponseSchemaResponseTransformer(data);
    return data;
};

export const patchAdminFileSharesByShortIdResponseTransformer = async (data: any): Promise<PatchAdminFileSharesByShortIdResponse> => {
    data = fileShareResponseSchemaResponseTransformer(data);
    return data;
};

const inviteSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data.expireAt) {
        data.expireAt = new Date(data.expireAt);
    }
    if (data.creator) {
        data.creator = userSchemaResponseTransformer(data.creator);
    }
    if (data.usedBy) {
        data.usedBy = data.usedBy.map((item: any) => userSchemaResponseTransformer(item));
    }
    return data;
};

export const getAdminInvitationsResponseTransformer = async (data: any): Promise<GetAdminInvitationsResponse> => {
    data = data.map((item: any) => inviteSchemaResponseTransformer(item));
    return data;
};

export const postAdminInvitationsResponseTransformer = async (data: any): Promise<PostAdminInvitationsResponse> => {
    data = inviteSchemaResponseTransformer(data);
    return data;
};

export const getAdminInvitationsByIdResponseTransformer = async (data: any): Promise<GetAdminInvitationsByIdResponse> => {
    data = inviteSchemaResponseTransformer(data);
    return data;
};

export const getAdminInvitationsByIdUsersResponseTransformer = async (data: any): Promise<GetAdminInvitationsByIdUsersResponse> => {
    data = data.map((item: any) => userSchemaResponseTransformer(item));
    return data;
};

const shortcodeDetailSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const getAdminShortcodesResponseTransformer = async (data: any): Promise<GetAdminShortcodesResponse> => {
    data = data.map((item: any) => shortcodeDetailSchemaResponseTransformer(item));
    return data;
};

export const postAdminShortcodesResponseTransformer = async (data: any): Promise<PostAdminShortcodesResponse> => {
    data = shortcodeDetailSchemaResponseTransformer(data);
    return data;
};

export const getAdminShortcodesByIdResponseTransformer = async (data: any): Promise<GetAdminShortcodesByIdResponse> => {
    data = shortcodeDetailSchemaResponseTransformer(data);
    return data;
};

export const putAdminShortcodesByIdResponseTransformer = async (data: any): Promise<PutAdminShortcodesByIdResponse> => {
    data = shortcodeDetailSchemaResponseTransformer(data);
    return data;
};

export const patchAdminShortcodesByIdStatusResponseTransformer = async (data: any): Promise<PatchAdminShortcodesByIdStatusResponse> => {
    data = shortcodeDetailSchemaResponseTransformer(data);
    return data;
};

export const getAdminStickerSetsResponseTransformer = async (data: any): Promise<GetAdminStickerSetsResponse> => {
    data = data.map((item: any) => stickerSetResponseSchemaResponseTransformer(item));
    return data;
};

export const postAdminStickerSetsResponseTransformer = async (data: any): Promise<PostAdminStickerSetsResponse> => {
    data = stickerSetResponseSchemaResponseTransformer(data);
    return data;
};

export const getAdminStickerSetsByIdResponseTransformer = async (data: any): Promise<GetAdminStickerSetsByIdResponse> => {
    data = stickerSetDetailResponseSchemaResponseTransformer(data);
    return data;
};

export const putAdminStickerSetsByIdResponseTransformer = async (data: any): Promise<PutAdminStickerSetsByIdResponse> => {
    data = stickerSetResponseSchemaResponseTransformer(data);
    return data;
};

const uploadedStickerResponseSchemaResponseTransformer = (data: any) => {
    if (data.expiresAt) {
        data.expiresAt = new Date(data.expiresAt);
    }
    return data;
};

export const postAdminStickerSetsByIdStickersResponseTransformer = async (data: any): Promise<PostAdminStickerSetsByIdStickersResponse> => {
    data = data.map((item: any) => uploadedStickerResponseSchemaResponseTransformer(item));
    return data;
};

const updateStickerResponseSchemaResponseTransformer = (data: any) => {
    if (data.expiresAt) {
        data.expiresAt = new Date(data.expiresAt);
    }
    return data;
};

export const putAdminStickerSetsByIdStickersByStickerIdResponseTransformer = async (data: any): Promise<PutAdminStickerSetsByIdStickersByStickerIdResponse> => {
    data = updateStickerResponseSchemaResponseTransformer(data);
    return data;
};

const s3ObjectResponseSchemaResponseTransformer = (data: any) => {
    if (data.lastModified) {
        data.lastModified = new Date(data.lastModified);
    }
    return data;
};

export const getAdminStorageBucketByBucketNameFilesResponseTransformer = async (data: any): Promise<GetAdminStorageBucketByBucketNameFilesResponse> => {
    data = data.map((item: any) => s3ObjectResponseSchemaResponseTransformer(item));
    return data;
};

const s3ObjectMetadataResponseSchemaResponseTransformer = (data: any) => {
    if (data.lastModified) {
        data.lastModified = new Date(data.lastModified);
    }
    return data;
};

export const getAdminStorageBucketByBucketNameFileResponseTransformer = async (data: any): Promise<GetAdminStorageBucketByBucketNameFileResponse> => {
    data = s3ObjectMetadataResponseSchemaResponseTransformer(data);
    return data;
};

const presignedUrlResponseSchemaResponseTransformer = (data: any) => {
    if (data.expiresAt) {
        data.expiresAt = new Date(data.expiresAt);
    }
    return data;
};

export const postAdminStorageBucketByBucketNamePresignUploadResponseTransformer = async (data: any): Promise<PostAdminStorageBucketByBucketNamePresignUploadResponse> => {
    data = presignedUrlResponseSchemaResponseTransformer(data);
    return data;
};

export const getAdminStorageBucketByBucketNamePresignDownloadResponseTransformer = async (data: any): Promise<GetAdminStorageBucketByBucketNamePresignDownloadResponse> => {
    data = presignedUrlResponseSchemaResponseTransformer(data);
    return data;
};

const bucketResponseSchemaResponseTransformer = (data: any) => {
    if (data.creationDate) {
        data.creationDate = new Date(data.creationDate);
    }
    return data;
};

export const getAdminStorageBucketsResponseTransformer = async (data: any): Promise<GetAdminStorageBucketsResponse> => {
    data = data.map((item: any) => bucketResponseSchemaResponseTransformer(item));
    return data;
};

export const getAdminUsersResponseTransformer = async (data: any): Promise<GetAdminUsersResponse> => {
    data = data.map((item: any) => userSchemaResponseTransformer(item));
    return data;
};
