// This file is auto-generated by @hey-api/openapi-ts

import type { GetAdminInvitationsByIdResponse, GetAdminInvitationsByIdUsersResponse, GetAdminInvitationsResponse, GetAdminShortcodesByIdResponse, GetAdminShortcodesResponse, GetAdminUsersResponse, GetArticlesByIdResponse, GetArticlesResponse, GetAuthWebauthnCredentialsResponse, GetCommentsArticleByArticleIdResponse, GetCommentsByIdRepliesResponse, GetUserOauthAuthorizationsResponse, GetUserOauthTokensResponse, GetUserProfileResponse, PatchAdminShortcodesByIdStatusResponse, PostAdminInvitationsResponse, PostAdminShortcodesResponse, PostArticlesResponse, PostAuthLoginResponse, PostAuthRegisterResponse, PostAuthRenewResponse, PostCommentsResponse, PutAdminShortcodesByIdResponse, PutArticlesByIdResponse, PutCommentsByIdResponse } from './types.gen';

const articleResponseSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const getArticlesResponseTransformer = async (data: any): Promise<GetArticlesResponse> => {
    data = data.map((item: any) => articleResponseSchemaResponseTransformer(item));
    return data;
};

export const postArticlesResponseTransformer = async (data: any): Promise<PostArticlesResponse> => {
    data = articleResponseSchemaResponseTransformer(data);
    return data;
};

export const getArticlesByIdResponseTransformer = async (data: any): Promise<GetArticlesByIdResponse> => {
    data = articleResponseSchemaResponseTransformer(data);
    return data;
};

export const putArticlesByIdResponseTransformer = async (data: any): Promise<PutArticlesByIdResponse> => {
    data = articleResponseSchemaResponseTransformer(data);
    return data;
};

const userSchemaResponseTransformer = (data: any) => {
    if (data.registerTime) {
        data.registerTime = new Date(data.registerTime);
    }
    return data;
};

const tokenRenewResponseSchemaResponseTransformer = (data: any) => {
    if (data.user) {
        data.user = userSchemaResponseTransformer(data.user);
    }
    if (data.expires) {
        data.expires = new Date(data.expires);
    }
    return data;
};

const authResponseSchemaResponseTransformer = (data: any) => {
    if (data.data) {
        data.data = tokenRenewResponseSchemaResponseTransformer(data.data);
    }
    return data;
};

export const postAuthLoginResponseTransformer = async (data: any): Promise<PostAuthLoginResponse> => {
    data = authResponseSchemaResponseTransformer(data);
    return data;
};

export const postAuthRegisterResponseTransformer = async (data: any): Promise<PostAuthRegisterResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

export const postAuthRenewResponseTransformer = async (data: any): Promise<PostAuthRenewResponse> => {
    data = tokenRenewResponseSchemaResponseTransformer(data);
    return data;
};

const commentResponseSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const getCommentsArticleByArticleIdResponseTransformer = async (data: any): Promise<GetCommentsArticleByArticleIdResponse> => {
    data = data.map((item: any) => commentResponseSchemaResponseTransformer(item));
    return data;
};

export const getCommentsByIdRepliesResponseTransformer = async (data: any): Promise<GetCommentsByIdRepliesResponse> => {
    data = data.map((item: any) => commentResponseSchemaResponseTransformer(item));
    return data;
};

export const postCommentsResponseTransformer = async (data: any): Promise<PostCommentsResponse> => {
    data = commentResponseSchemaResponseTransformer(data);
    return data;
};

export const putCommentsByIdResponseTransformer = async (data: any): Promise<PutCommentsByIdResponse> => {
    data = commentResponseSchemaResponseTransformer(data);
    return data;
};

export const getUserProfileResponseTransformer = async (data: any): Promise<GetUserProfileResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

const oAuthConsentResponseSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    return data;
};

export const getUserOauthAuthorizationsResponseTransformer = async (data: any): Promise<GetUserOauthAuthorizationsResponse> => {
    data = data.map((item: any) => oAuthConsentResponseSchemaResponseTransformer(item));
    return data;
};

const oAuthTokenResponseSchemaResponseTransformer = (data: any) => {
    if (data.expiresAt) {
        data.expiresAt = new Date(data.expiresAt);
    }
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    return data;
};

export const getUserOauthTokensResponseTransformer = async (data: any): Promise<GetUserOauthTokensResponse> => {
    data = data.map((item: any) => oAuthTokenResponseSchemaResponseTransformer(item));
    return data;
};

const userCredentialSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    return data;
};

export const getAuthWebauthnCredentialsResponseTransformer = async (data: any): Promise<GetAuthWebauthnCredentialsResponse> => {
    data = data.map((item: any) => userCredentialSchemaResponseTransformer(item));
    return data;
};

const inviteSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data.expireAt) {
        data.expireAt = new Date(data.expireAt);
    }
    if (data.creator) {
        data.creator = userSchemaResponseTransformer(data.creator);
    }
    if (data.usedBy) {
        data.usedBy = data.usedBy.map((item: any) => userSchemaResponseTransformer(item));
    }
    return data;
};

export const getAdminInvitationsResponseTransformer = async (data: any): Promise<GetAdminInvitationsResponse> => {
    data = data.map((item: any) => inviteSchemaResponseTransformer(item));
    return data;
};

export const postAdminInvitationsResponseTransformer = async (data: any): Promise<PostAdminInvitationsResponse> => {
    data = inviteSchemaResponseTransformer(data);
    return data;
};

export const getAdminInvitationsByIdResponseTransformer = async (data: any): Promise<GetAdminInvitationsByIdResponse> => {
    data = inviteSchemaResponseTransformer(data);
    return data;
};

export const getAdminInvitationsByIdUsersResponseTransformer = async (data: any): Promise<GetAdminInvitationsByIdUsersResponse> => {
    data = data.map((item: any) => userSchemaResponseTransformer(item));
    return data;
};

const shortcodeDetailSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const getAdminShortcodesResponseTransformer = async (data: any): Promise<GetAdminShortcodesResponse> => {
    data = data.map((item: any) => shortcodeDetailSchemaResponseTransformer(item));
    return data;
};

export const postAdminShortcodesResponseTransformer = async (data: any): Promise<PostAdminShortcodesResponse> => {
    data = shortcodeDetailSchemaResponseTransformer(data);
    return data;
};

export const getAdminShortcodesByIdResponseTransformer = async (data: any): Promise<GetAdminShortcodesByIdResponse> => {
    data = shortcodeDetailSchemaResponseTransformer(data);
    return data;
};

export const putAdminShortcodesByIdResponseTransformer = async (data: any): Promise<PutAdminShortcodesByIdResponse> => {
    data = shortcodeDetailSchemaResponseTransformer(data);
    return data;
};

export const patchAdminShortcodesByIdStatusResponseTransformer = async (data: any): Promise<PatchAdminShortcodesByIdStatusResponse> => {
    data = shortcodeDetailSchemaResponseTransformer(data);
    return data;
};

export const getAdminUsersResponseTransformer = async (data: any): Promise<GetAdminUsersResponse> => {
    data = data.map((item: any) => userSchemaResponseTransformer(item));
    return data;
};
