// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5170/' | (string & {});
};

export type AuthLoginModel = {
    email: string;
    password: string;
    captchaToken?: null | string;
};

export type PostAuthLoginData = {
    body: AuthLoginModel;
    path?: never;
    query?: never;
    url: '/Auth/login';
};

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUserInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/User/info';
};

export type GetUserInfoResponses = {
    /**
     * OK
     */
    200: unknown;
};
