// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5170/' | (string & {});
};

export type AuthLoginModel = {
    email: string;
    password: string;
    captchaToken?: null | string;
};

export type AuthRegisterModel = {
    username: string;
    email: string;
    password: string;
    inviteCode?: null | string;
    captchaToken?: null | string;
};

export type AuthResponse = {
    message?: string;
    user?: UserTable;
    expires?: Date;
};

export type CreateInvitationRequest = {
    uses: number | string;
    hoursValid: number | string;
};

export type IFormFile = Blob | File;

export type InviteTable = {
    id?: number | string;
    code?: string;
    creatorId?: number | string;
    createdAt?: Date;
    expireAt?: null | Date;
    maxUses?: number | string;
    usedCount?: number | string;
    isDisabled?: boolean;
    creator?: null | UserTable;
    usedBy?: null | Array<UserTable>;
};

export type MessageResponse = {
    message?: string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type UpdateInvitationRequest = {
    isDisabled: null | boolean;
    uses: null | number | string;
    hoursValid: null | number | string;
};

export type UpdateProfileModel = {
    newPassword?: null | string;
    username?: null | string;
    oldPassword?: null | string;
};

export type UserRole = number;

export type UserTable = {
    id?: number | string;
    username?: string;
    email?: string;
    role?: UserRole;
    isBanned?: boolean;
    registerTime?: Date;
    avatar?: string;
    usedInviteId?: null | number | string;
    usedInvite?: null | InviteTable;
};

export type PostAuthLoginData = {
    body: AuthLoginModel;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Forbidden
     */
    403: MessageResponse;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostAuthRegisterData = {
    body: AuthRegisterModel;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Forbidden
     */
    403: MessageResponse;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * OK
     */
    200: UserTable;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type PostAuthRenewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/renew';
};

export type PostAuthRenewErrors = {
    /**
     * Unauthorized
     */
    401: MessageResponse;
};

export type PostAuthRenewError = PostAuthRenewErrors[keyof PostAuthRenewErrors];

export type PostAuthRenewResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type PostAuthRenewResponse = PostAuthRenewResponses[keyof PostAuthRenewResponses];

export type GetUserProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/profile';
};

export type GetUserProfileResponses = {
    /**
     * OK
     */
    200: UserTable;
};

export type GetUserProfileResponse = GetUserProfileResponses[keyof GetUserProfileResponses];

export type PostUserProfileData = {
    body: UpdateProfileModel;
    path?: never;
    query?: never;
    url: '/user/profile';
};

export type PostUserProfileErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
};

export type PostUserProfileError = PostUserProfileErrors[keyof PostUserProfileErrors];

export type PostUserProfileResponses = {
    /**
     * OK
     */
    200: MessageResponse;
};

export type PostUserProfileResponse = PostUserProfileResponses[keyof PostUserProfileResponses];

export type PostUserAvatarData = {
    body: {
        file?: IFormFile;
    };
    path?: never;
    query?: never;
    url: '/user/avatar';
};

export type PostUserAvatarResponses = {
    /**
     * OK
     */
    200: MessageResponse;
};

export type PostUserAvatarResponse = PostUserAvatarResponses[keyof PostUserAvatarResponses];

export type GetAdminInvitationsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number | string;
        size?: number | string;
    };
    url: '/admin/invitations';
};

export type GetAdminInvitationsResponses = {
    /**
     * OK
     */
    200: Array<InviteTable>;
};

export type GetAdminInvitationsResponse = GetAdminInvitationsResponses[keyof GetAdminInvitationsResponses];

export type PostAdminInvitationsData = {
    body: CreateInvitationRequest;
    path?: never;
    query?: never;
    url: '/admin/invitations';
};

export type PostAdminInvitationsResponses = {
    /**
     * Created
     */
    201: InviteTable;
};

export type PostAdminInvitationsResponse = PostAdminInvitationsResponses[keyof PostAdminInvitationsResponses];

export type DeleteAdminInvitationsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/invitations/{id}';
};

export type DeleteAdminInvitationsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteAdminInvitationsByIdError = DeleteAdminInvitationsByIdErrors[keyof DeleteAdminInvitationsByIdErrors];

export type DeleteAdminInvitationsByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetAdminInvitationsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/invitations/{id}';
};

export type GetAdminInvitationsByIdResponses = {
    /**
     * OK
     */
    200: InviteTable;
};

export type GetAdminInvitationsByIdResponse = GetAdminInvitationsByIdResponses[keyof GetAdminInvitationsByIdResponses];

export type PutAdminInvitationsByIdData = {
    body: UpdateInvitationRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/invitations/{id}';
};

export type PutAdminInvitationsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutAdminInvitationsByIdError = PutAdminInvitationsByIdErrors[keyof PutAdminInvitationsByIdErrors];

export type PutAdminInvitationsByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetAdminInvitationsByIdUsersData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        page?: number | string;
        size?: number | string;
    };
    url: '/admin/invitations/{id}/users';
};

export type GetAdminInvitationsByIdUsersResponses = {
    /**
     * OK
     */
    200: Array<UserTable>;
};

export type GetAdminInvitationsByIdUsersResponse = GetAdminInvitationsByIdUsersResponses[keyof GetAdminInvitationsByIdUsersResponses];

export type GetAdminUsersData = {
    body?: never;
    path?: never;
    query?: {
        page?: number | string;
        size?: number | string;
    };
    url: '/admin/users';
};

export type GetAdminUsersResponses = {
    /**
     * OK
     */
    200: Array<UserTable>;
};

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses];

export type PutAdminUsersByIdStatusData = {
    body: boolean;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/users/{id}/status';
};

export type PutAdminUsersByIdStatusErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutAdminUsersByIdStatusError = PutAdminUsersByIdStatusErrors[keyof PutAdminUsersByIdStatusErrors];

export type PutAdminUsersByIdStatusResponses = {
    /**
     * No Content
     */
    204: unknown;
};
