// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5170/' | (string & {});
};

export type AddressFamily = number;

export type Algorithm = number;

export type ArticleCreateModel = {
    title: string;
    content: string;
    isPublished?: boolean;
};

export type ArticleResponse = {
    id?: number | string;
    title?: string;
    content?: string;
    authorId?: number | string;
    authorUsername?: null | string;
    createdAt?: Date;
    updatedAt?: Date;
    isPublished?: boolean;
    commentCount?: number | string;
};

export type ArticleUpdateModel = {
    title: string;
    content: string;
    isPublished?: boolean;
};

export type AsnEncodedData = {
    oid?: null | Oid;
    rawData?: string;
};

export type AssertionOptions = {
    challenge?: unknown;
    timeout?: number | string;
    rpId?: null | string;
    allowCredentials?: Array<PublicKeyCredentialDescriptor>;
    userVerification?: null | UserVerificationRequirement;
    hints?: Array<unknown>;
    extensions?: null | AuthenticationExtensionsClientInputs;
};

export type AssertionResponse = {
    authenticatorData: unknown;
    signature: unknown;
    clientDataJSON: unknown;
    userHandle?: unknown;
};

export type AsymmetricAlgorithm = {
    keySize?: number | string;
    legalKeySizes?: null | Array<KeySizes>;
    signatureAlgorithm?: null | string;
    keyExchangeAlgorithm?: null | string;
};

export type AttestationConveyancePreference = unknown;

export type AttestationResponse = {
    attestationObject: unknown;
    clientDataJSON: unknown;
    transports: null | Array<unknown>;
};

export type AuthenticationExtensionsClientInputs = {
    'example.extension.bool'?: null | boolean;
    exts?: null | boolean;
    uvm?: null | boolean;
    credProps?: null | boolean;
    prf?: null | AuthenticationExtensionsPrfInputs;
    largeBlob?: null | AuthenticationExtensionsLargeBlobInputs;
    credentialProtectionPolicy?: null | CredentialProtectionPolicy;
    enforceCredentialProtectionPolicy?: null | boolean;
};

export type AuthenticationExtensionsClientOutputs = {
    'example.extension.bool'?: null | boolean;
    appid?: boolean;
    exts?: null | Array<string>;
    uvm?: null | Array<Array<number | string>>;
    credProps?: null | CredentialPropertiesOutput;
    prf?: null | AuthenticationExtensionsPrfOutputs;
    largeBlob?: null | AuthenticationExtensionsLargeBlobOutputs;
    credProtect?: null | CredentialProtectionPolicy;
};

export type AuthenticationExtensionsLargeBlobInputs = {
    support?: null | LargeBlobSupport;
    read?: boolean;
    write?: unknown;
};

export type AuthenticationExtensionsLargeBlobOutputs = {
    supported?: boolean;
    blob?: unknown;
    written?: boolean;
};

export type AuthenticationExtensionsPrfInputs = {
    eval?: AuthenticationExtensionsPrfValues;
    evalByCredential?: null | KeyValuePairOfstringAndAuthenticationExtensionsPrfValues;
};

export type AuthenticationExtensionsPrfOutputs = {
    enabled?: boolean;
    results?: AuthenticationExtensionsPrfValues;
};

export type AuthenticationExtensionsPrfValues = {
    first: unknown;
    second?: unknown;
};

export type AuthenticatorAssertionRawResponse = {
    id: null | string;
    rawId: unknown;
    response?: AssertionResponse;
    type: PublicKeyCredentialType;
    extensions?: AuthenticationExtensionsClientOutputs;
    clientExtensionResults: AuthenticationExtensionsClientOutputs;
};

export type AuthenticatorAttachment = unknown;

export type AuthenticatorAttestationRawResponse = {
    id: null | string;
    rawId: unknown;
    type: PublicKeyCredentialType;
    response: AttestationResponse;
    extensions?: AuthenticationExtensionsClientOutputs;
    clientExtensionResults: AuthenticationExtensionsClientOutputs;
};

export type AuthenticatorSelection = {
    authenticatorAttachment?: null | AuthenticatorAttachment;
    residentKey?: ResidentKeyRequirement;
    requireResidentKey?: boolean;
    userVerification?: UserVerificationRequirement;
};

export type AuthLoginModel = {
    email: string;
    password: string;
    captchaToken?: null | string;
};

export type AuthRegisterModel = {
    username: string;
    email: string;
    password: string;
    inviteCode?: null | string;
    captchaToken?: null | string;
};

export type AuthResponse = {
    status?: string;
    data?: TokenRenewResponse;
};

export type CancellationToken = {
    isCancellationRequested?: boolean;
    canBeCanceled?: boolean;
    waitHandle?: WaitHandle;
};

export type Claim = {
    issuer?: null | string;
    originalIssuer?: null | string;
    properties?: null | {
        [key: string]: string;
    };
    subject?: ClaimsIdentity;
    type?: null | string;
    value?: null | string;
    valueType?: null | string;
};

export type ClaimsIdentity = {
    authenticationType?: null | string;
    isAuthenticated?: boolean;
    actor?: null | ClaimsIdentity;
    bootstrapContext?: unknown;
    claims?: unknown;
    label?: null | string;
    name?: null | string;
    nameClaimType?: null | string;
    roleClaimType?: null | string;
};

export type ClaimsPrincipal = {
    claims?: null | Array<Claim>;
    identities?: null | Array<ClaimsIdentity>;
    identity?: IIdentity;
};

export type CommentCreateModel = {
    content: string;
    parentCommentId?: null | number | string;
};

export type CommentResponse = {
    id?: number | string;
    content?: string;
    articleId?: number | string;
    authorId?: number | string;
    authorUsername?: null | string;
    parentCommentId?: null | number | string;
    createdAt?: Date;
    updatedAt?: Date;
    isDeleted?: boolean;
    replyCount?: number | string;
};

export type CommentUpdateModel = {
    content: string;
};

export type ConnectionInfo = {
    id?: string;
    remoteIpAddress?: null | IpAddress;
    remotePort?: number | string;
    localIpAddress?: null | IpAddress;
    localPort?: number | string;
    clientCertificate?: null | X509Certificate2;
};

export type CreateAppRequest = {
    displayName: string;
    redirectUris: null | Array<string>;
    clientType?: null | string;
    applicationType?: null | string;
};

export type CreateAppResponse = {
    id: string;
    clientId: string;
    clientSecret: string;
    displayName: string;
};

export type CreateInvitationRequest = {
    uses: number | string;
    hoursValid: number | string;
};

export type CredentialCreateOptions = {
    rp: PublicKeyCredentialRpEntity;
    user: Fido2User;
    challenge: unknown;
    pubKeyCredParams: Array<PubKeyCredParam>;
    timeout?: number | string;
    attestation?: AttestationConveyancePreference;
    attestationFormats?: Array<unknown>;
    authenticatorSelection?: AuthenticatorSelection;
    hints?: Array<unknown>;
    excludeCredentials?: Array<PublicKeyCredentialDescriptor>;
    extensions?: null | AuthenticationExtensionsClientInputs;
};

export type CredentialPropertiesOutput = {
    rk?: boolean;
    authenticatorDisplayName?: null | string;
};

export type CredentialProtectionPolicy = unknown;

export type CredentialUpdateModel = {
    nickname?: null | string;
};

export type Fido2User = {
    name?: null | string;
    id?: unknown;
    displayName?: null | string;
};

export type HomeAppearanceResponse = {
    backgroundUrl?: string;
    backgroundBlur?: number | string;
    backgroundOpacity?: number | string;
    bannerContent?: string;
    bannerDisplayMode?: string;
};

export type HostString = {
    value?: null | string;
    hasValue?: boolean;
    host?: null | string;
    port?: null | number | string;
};

export type HttpContext = {
    features?: null | Array<KeyValuePairOfTypeAndObject>;
    request?: HttpRequest;
    response?: HttpResponse;
    connection?: ConnectionInfo;
    webSockets?: WebSocketManager;
    user?: ClaimsPrincipal;
    items?: {
        [key: string]: unknown;
    };
    requestServices?: IServiceProvider;
    requestAborted?: CancellationToken;
    traceIdentifier?: string;
    session?: ISession;
};

export type HttpRequest = {
    httpContext?: HttpContext;
    method?: string;
    scheme?: string;
    isHttps?: boolean;
    host?: HostString;
    pathBase?: PathString;
    path?: PathString;
    queryString?: QueryString;
    query?: Array<KeyValuePairOfstringAndStringValues>;
    protocol?: string;
    headers?: null | {
        [key: string]: Array<string>;
    };
    cookies?: Array<KeyValuePairOfstringAndstring>;
    contentLength?: null | bigint | string;
    contentType?: null | string;
    body?: Stream;
    bodyReader?: PipeReader;
    hasFormContentType?: boolean;
    form?: Array<KeyValuePairOfstringAndStringValues>;
    routeValues?: {
        [key: string]: unknown;
    };
};

export type HttpResponse = {
    httpContext?: HttpContext;
    statusCode?: number | string;
    headers?: null | {
        [key: string]: Array<string>;
    };
    body?: Stream;
    bodyWriter?: PipeWriter;
    contentLength?: null | bigint | string;
    contentType?: null | string;
    cookies?: IResponseCookies;
    hasStarted?: boolean;
};

export type IFormFile = Blob | File;

export type IIdentity = {
    name?: null | string;
    authenticationType?: null | string;
    isAuthenticated?: boolean;
};

export type Invite = {
    id?: number | string;
    code?: string;
    creatorId?: number | string;
    createdAt?: Date;
    expireAt?: null | Date;
    maxUses?: number | string;
    usedCount?: number | string;
    isDisabled?: boolean;
    creator?: null | User;
    usedBy?: null | Array<User>;
    isValid?: boolean;
};

export type IpAddress = {
    addressFamily?: AddressFamily;
    scopeId?: bigint | string;
    isIPv6Multicast?: boolean;
    isIPv6LinkLocal?: boolean;
    isIPv6SiteLocal?: boolean;
    isIPv6Teredo?: boolean;
    isIPv6UniqueLocal?: boolean;
    isIPv4MappedToIPv6?: boolean;
    address?: bigint | string;
};

export type IResponseCookies = {
    [key: string]: unknown;
};

export type IServiceProvider = {
    [key: string]: unknown;
};

export type ISession = {
    isAvailable?: boolean;
    id?: null | string;
    keys?: null | Array<string>;
};

export type KeySizes = {
    minSize: number | string;
    maxSize: number | string;
    skipSize: number | string;
};

export type KeyValuePairOfstringAndAuthenticationExtensionsPrfValues = {
    key: null | string;
    value: AuthenticationExtensionsPrfValues;
};

export type KeyValuePairOfstringAndstring = {
    key: null | string;
    value: null | string;
};

export type KeyValuePairOfstringAndStringValues = {
    key: null | string;
    value: Array<string>;
};

export type KeyValuePairOfTypeAndObject = {
    key: Type;
    value: unknown;
};

export type LargeBlobSupport = unknown;

export type MessageResponse = {
    message?: string;
};

export type NewSecretResponse = {
    clientSecret: string;
};

export type OAuth2ApproveRequest = {
    clientId: string;
    redirectUri: string;
    scope?: null | string;
    approved?: boolean;
    state?: null | string;
    codeChallenge?: null | string;
    codeChallengeMethod?: null | string;
};

export type OAuth2ApproveResultResponse = {
    success?: boolean;
    redirectUrl?: null | string;
    error?: null | string;
    errorDescription?: null | string;
};

export type OAuth2AuthorizeResponse = {
    clientId?: string;
    appName?: string;
    description?: null | string;
    homepage?: null | string;
    redirectUri?: string;
    scopes?: Array<string>;
    scopeDescriptions?: {
        [key: string]: string;
    };
    state?: null | string;
    userId?: number | string;
    appCreator?: null | string;
};

export type OAuth2ErrorResponse = {
    error?: string;
    errorDescription?: null | string;
};

export type OAuth2TokenResponse = {
    accessToken?: string;
    tokenType?: string;
    expiresIn?: number | string;
    refreshToken?: null | string;
    scope?: null | string;
};

export type OAuthAppDetailResponse = {
    id?: string;
    clientId?: string;
    displayName?: string;
    userId?: null | string;
    redirectUris?: Array<string>;
    clientType?: string;
    applicationType?: string;
    consentType?: string;
};

export type OAuthAppResponse = {
    id?: string;
    clientId?: string;
    displayName?: string;
    userId?: null | string;
    clientType?: string;
    applicationType?: string;
    consentType?: string;
};

export type OAuthConsentResponse = {
    id?: string;
    applicationId?: string;
    clientId?: string;
    displayName?: string;
    createdAt?: Date;
};

export type OAuthTokenResponse = {
    id?: string;
    applicationId?: string;
    clientId?: string;
    displayName?: string;
    tokenType?: string;
    expiresAt?: Date;
    createdAt?: Date;
};

export type Oid = {
    value?: null | string;
    friendlyName?: null | string;
};

export type PatchAppRequest = {
    displayName?: null | string;
    redirectUris?: null | Array<string>;
    clientType?: null | string;
    applicationType?: null | string;
};

export type PathString = {
    value?: null | string;
    hasValue?: boolean;
};

export type PipeReader = null | Blob | File;

export type PipeWriter = {
    canGetUnflushedBytes?: boolean;
    unflushedBytes?: bigint | string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type PubKeyCredParam = {
    type?: unknown;
    alg: Algorithm;
};

export type PublicKey = {
    encodedKeyValue?: AsnEncodedData;
    encodedParameters?: AsnEncodedData;
    key?: AsymmetricAlgorithm;
    oid?: Oid;
};

export type PublicKeyCredentialDescriptor = {
    type: PublicKeyCredentialType;
    id: unknown;
    transports?: null | Array<unknown>;
};

export type PublicKeyCredentialRpEntity = {
    id: string;
    name: string;
    icon?: null | string;
};

export type PublicKeyCredentialType = unknown;

export type QueryString = {
    value?: null | string;
    hasValue?: boolean;
};

export type ReadOnlyMemoryOfbyte = string;

export type ResidentKeyRequirement = unknown;

export type SafeWaitHandle = {
    isInvalid?: boolean;
    isClosed?: boolean;
};

export type SeoMetaResponse = {
    title?: string;
    description?: string;
    keywords?: null | string;
    ogTitle?: null | string;
    ogDescription?: null | string;
    ogImage?: null | string;
    twitterCard?: string;
    robots?: string;
};

export type SiteInitResponse = {
    seo?: SeoMetaResponse;
    home?: HomeAppearanceResponse;
    registrationEnabled?: boolean;
};

export type Stream = Blob | File;

export type TokenRenewResponse = {
    message?: string;
    user?: User;
    expires?: null | Date;
};

export type TotpSetupResponse = {
    secret?: string;
    url?: string;
};

export type TotpVerifyRequest = {
    code?: string;
};

export type TwoFactorPolicyResponse = {
    totp?: TwoFactorStatus;
    forceTwoFactor?: boolean;
};

export type TwoFactorStatus = {
    enabled?: boolean;
};

export type Type = unknown;

export type UpdateAppRequest = {
    displayName: string;
    redirectUris: null | Array<string>;
    clientType?: null | string;
    applicationType?: null | string;
};

export type UpdateInvitationRequest = {
    isDisabled: null | boolean;
    uses: null | number | string;
    hoursValid: null | number | string;
};

export type UpdateProfileModel = {
    newPassword?: null | string;
    username?: null | string;
    oldPassword?: null | string;
};

export type UpdateUserStatusBody = {
    isBanned?: boolean;
};

export type User = {
    id?: number | string;
    username?: string;
    email?: string;
    role?: UserRole;
    isBanned?: boolean;
    registerTime?: Date;
    avatar?: string;
    usedInviteId?: null | number | string;
};

export type UserCredential = {
    id?: number | string;
    credentialId?: string;
    publicKey?: string;
    createdAt?: Date;
    signatureCounter?: number | string;
    nickname?: string;
    userId?: number | string;
};

export type UserRole = number;

export type UserVerificationRequirement = unknown;

export type WaitHandle = {
    handle?: unknown;
    safeWaitHandle?: null | SafeWaitHandle;
};

export type WebSocketManager = {
    isWebSocketRequest?: boolean;
    webSocketRequestedProtocols?: null | Array<string>;
};

export type X500DistinguishedName = {
    name?: null | string;
    oid?: null | Oid;
    rawData?: string;
};

export type X509Certificate2 = {
    archived?: boolean;
    extensions?: null | Array<X509Extension>;
    friendlyName?: string;
    hasPrivateKey?: boolean;
    privateKey?: null | AsymmetricAlgorithm;
    issuerName?: X500DistinguishedName;
    notAfter?: Date;
    notBefore?: Date;
    publicKey?: PublicKey;
    rawData?: null | string;
    rawDataMemory?: ReadOnlyMemoryOfbyte;
    serialNumber?: null | string;
    signatureAlgorithm?: Oid;
    subjectName?: X500DistinguishedName;
    thumbprint?: null | string;
    version?: number | string;
    handle?: unknown;
    issuer?: null | string;
    subject?: null | string;
    serialNumberBytes?: ReadOnlyMemoryOfbyte;
};

export type X509Extension = {
    critical?: boolean;
    oid?: null | Oid;
    rawData?: string;
};

export type GetArticlesData = {
    body?: never;
    path?: never;
    query?: {
        page?: number | string;
        pageSize?: number | string;
        published?: boolean;
    };
    url: '/articles';
};

export type GetArticlesResponses = {
    /**
     * OK
     */
    200: Array<ArticleResponse>;
};

export type GetArticlesResponse = GetArticlesResponses[keyof GetArticlesResponses];

export type PostArticlesData = {
    body: ArticleCreateModel;
    path?: never;
    query?: never;
    url: '/articles';
};

export type PostArticlesErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
};

export type PostArticlesError = PostArticlesErrors[keyof PostArticlesErrors];

export type PostArticlesResponses = {
    /**
     * Created
     */
    201: ArticleResponse;
};

export type PostArticlesResponse = PostArticlesResponses[keyof PostArticlesResponses];

export type DeleteArticlesByIdData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/articles/{id}';
};

export type DeleteArticlesByIdErrors = {
    /**
     * Forbidden
     */
    403: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
};

export type DeleteArticlesByIdError = DeleteArticlesByIdErrors[keyof DeleteArticlesByIdErrors];

export type DeleteArticlesByIdResponses = {
    /**
     * OK
     */
    200: MessageResponse;
};

export type DeleteArticlesByIdResponse = DeleteArticlesByIdResponses[keyof DeleteArticlesByIdResponses];

export type GetArticlesByIdData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/articles/{id}';
};

export type GetArticlesByIdErrors = {
    /**
     * Not Found
     */
    404: MessageResponse;
};

export type GetArticlesByIdError = GetArticlesByIdErrors[keyof GetArticlesByIdErrors];

export type GetArticlesByIdResponses = {
    /**
     * OK
     */
    200: ArticleResponse;
};

export type GetArticlesByIdResponse = GetArticlesByIdResponses[keyof GetArticlesByIdResponses];

export type PutArticlesByIdData = {
    body: ArticleUpdateModel;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/articles/{id}';
};

export type PutArticlesByIdErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Forbidden
     */
    403: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
};

export type PutArticlesByIdError = PutArticlesByIdErrors[keyof PutArticlesByIdErrors];

export type PutArticlesByIdResponses = {
    /**
     * OK
     */
    200: ArticleResponse;
};

export type PutArticlesByIdResponse = PutArticlesByIdResponses[keyof PutArticlesByIdResponses];

export type PostAuthLoginData = {
    body: AuthLoginModel;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Forbidden
     */
    403: MessageResponse;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostAuthRegisterData = {
    body: AuthRegisterModel;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Forbidden
     */
    403: MessageResponse;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * OK
     */
    200: User;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type PostAuthRenewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/renew';
};

export type PostAuthRenewErrors = {
    /**
     * Unauthorized
     */
    401: MessageResponse;
};

export type PostAuthRenewError = PostAuthRenewErrors[keyof PostAuthRenewErrors];

export type PostAuthRenewResponses = {
    /**
     * OK
     */
    200: TokenRenewResponse;
};

export type PostAuthRenewResponse = PostAuthRenewResponses[keyof PostAuthRenewResponses];

export type GetCommentsArticleByArticleIdData = {
    body?: never;
    path: {
        articleId: number | string;
    };
    query?: {
        page?: number | string;
        pageSize?: number | string;
    };
    url: '/comments/article/{articleId}';
};

export type GetCommentsArticleByArticleIdResponses = {
    /**
     * OK
     */
    200: Array<CommentResponse>;
};

export type GetCommentsArticleByArticleIdResponse = GetCommentsArticleByArticleIdResponses[keyof GetCommentsArticleByArticleIdResponses];

export type GetCommentsByIdRepliesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        commentId?: number | string;
        page?: number | string;
        pageSize?: number | string;
    };
    url: '/comments/{id}/replies';
};

export type GetCommentsByIdRepliesResponses = {
    /**
     * OK
     */
    200: Array<CommentResponse>;
};

export type GetCommentsByIdRepliesResponse = GetCommentsByIdRepliesResponses[keyof GetCommentsByIdRepliesResponses];

export type PostCommentsData = {
    body: CommentCreateModel;
    path?: never;
    query?: {
        articleId?: number | string;
    };
    url: '/comments';
};

export type PostCommentsErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
};

export type PostCommentsError = PostCommentsErrors[keyof PostCommentsErrors];

export type PostCommentsResponses = {
    /**
     * Created
     */
    201: CommentResponse;
};

export type PostCommentsResponse = PostCommentsResponses[keyof PostCommentsResponses];

export type DeleteCommentsByIdData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/comments/{id}';
};

export type DeleteCommentsByIdErrors = {
    /**
     * Forbidden
     */
    403: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
};

export type DeleteCommentsByIdError = DeleteCommentsByIdErrors[keyof DeleteCommentsByIdErrors];

export type DeleteCommentsByIdResponses = {
    /**
     * OK
     */
    200: MessageResponse;
};

export type DeleteCommentsByIdResponse = DeleteCommentsByIdResponses[keyof DeleteCommentsByIdResponses];

export type PutCommentsByIdData = {
    body: CommentUpdateModel;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/comments/{id}';
};

export type PutCommentsByIdErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
    /**
     * Forbidden
     */
    403: MessageResponse;
    /**
     * Not Found
     */
    404: MessageResponse;
};

export type PutCommentsByIdError = PutCommentsByIdErrors[keyof PutCommentsByIdErrors];

export type PutCommentsByIdResponses = {
    /**
     * OK
     */
    200: CommentResponse;
};

export type PutCommentsByIdResponse = PutCommentsByIdResponses[keyof PutCommentsByIdResponses];

export type GetSettingsSeoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/seo';
};

export type GetSettingsSeoResponses = {
    /**
     * OK
     */
    200: SeoMetaResponse;
};

export type GetSettingsSeoResponse = GetSettingsSeoResponses[keyof GetSettingsSeoResponses];

export type GetSettingsHomeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/home';
};

export type GetSettingsHomeResponses = {
    /**
     * OK
     */
    200: HomeAppearanceResponse;
};

export type GetSettingsHomeResponse = GetSettingsHomeResponses[keyof GetSettingsHomeResponses];

export type GetSettingsInitData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/init';
};

export type GetSettingsInitResponses = {
    /**
     * OK
     */
    200: SiteInitResponse;
};

export type GetSettingsInitResponse = GetSettingsInitResponses[keyof GetSettingsInitResponses];

export type GetUserProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/profile';
};

export type GetUserProfileResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetUserProfileResponse = GetUserProfileResponses[keyof GetUserProfileResponses];

export type PostUserProfileData = {
    body: UpdateProfileModel;
    path?: never;
    query?: never;
    url: '/user/profile';
};

export type PostUserProfileErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
};

export type PostUserProfileError = PostUserProfileErrors[keyof PostUserProfileErrors];

export type PostUserProfileResponses = {
    /**
     * OK
     */
    200: MessageResponse;
};

export type PostUserProfileResponse = PostUserProfileResponses[keyof PostUserProfileResponses];

export type PostUserAvatarData = {
    body: {
        file?: IFormFile;
    };
    path?: never;
    query?: never;
    url: '/user/avatar';
};

export type PostUserAvatarResponses = {
    /**
     * OK
     */
    200: MessageResponse;
};

export type PostUserAvatarResponse = PostUserAvatarResponses[keyof PostUserAvatarResponses];

export type GetOauth2AuthorizeData = {
    body?: never;
    path?: never;
    query?: {
        ResponseType?: string;
        ClientId?: string;
        RedirectUri?: string;
        Scope?: string;
        State?: string;
        CodeChallenge?: string;
        CodeChallengeMethod?: string;
    };
    url: '/oauth2/authorize';
};

export type GetOauth2AuthorizeErrors = {
    /**
     * Bad Request
     */
    400: OAuth2ErrorResponse;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type GetOauth2AuthorizeError = GetOauth2AuthorizeErrors[keyof GetOauth2AuthorizeErrors];

export type GetOauth2AuthorizeResponses = {
    /**
     * OK
     */
    200: OAuth2AuthorizeResponse;
};

export type GetOauth2AuthorizeResponse = GetOauth2AuthorizeResponses[keyof GetOauth2AuthorizeResponses];

export type PostOauth2ApproveData = {
    body: OAuth2ApproveRequest;
    path?: never;
    query?: never;
    url: '/oauth2/approve';
};

export type PostOauth2ApproveErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type PostOauth2ApproveError = PostOauth2ApproveErrors[keyof PostOauth2ApproveErrors];

export type PostOauth2ApproveResponses = {
    /**
     * OK
     */
    200: OAuth2ApproveResultResponse;
};

export type PostOauth2ApproveResponse = PostOauth2ApproveResponses[keyof PostOauth2ApproveResponses];

export type PostOauth2TokenData = {
    body: {
        GrantType?: string;
        Code?: string;
        RedirectUri?: string;
        RefreshToken?: string;
        ClientId?: string;
        ClientSecret?: string;
        CodeVerifier?: string;
    };
    path?: never;
    query?: never;
    url: '/oauth2/token';
};

export type PostOauth2TokenErrors = {
    /**
     * Bad Request
     */
    400: OAuth2ErrorResponse;
    /**
     * Unauthorized
     */
    401: OAuth2ErrorResponse;
};

export type PostOauth2TokenError = PostOauth2TokenErrors[keyof PostOauth2TokenErrors];

export type PostOauth2TokenResponses = {
    /**
     * OK
     */
    200: OAuth2TokenResponse;
};

export type PostOauth2TokenResponse = PostOauth2TokenResponses[keyof PostOauth2TokenResponses];

export type PostOauth2RevokeData = {
    body: {
        Token?: string;
        TokenTypeHint?: string;
        ClientId?: string;
        ClientSecret?: string;
    };
    path?: never;
    query?: never;
    url: '/oauth2/revoke';
};

export type PostOauth2RevokeErrors = {
    /**
     * Unauthorized
     */
    401: OAuth2ErrorResponse;
};

export type PostOauth2RevokeError = PostOauth2RevokeErrors[keyof PostOauth2RevokeErrors];

export type PostOauth2RevokeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUserOauthAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/oauth/apps';
};

export type GetUserOauthAppsResponses = {
    /**
     * OK
     */
    200: Array<OAuthAppResponse>;
};

export type GetUserOauthAppsResponse = GetUserOauthAppsResponses[keyof GetUserOauthAppsResponses];

export type PostUserOauthAppData = {
    body: CreateAppRequest;
    path?: never;
    query?: never;
    url: '/user/oauth/app';
};

export type PostUserOauthAppErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostUserOauthAppError = PostUserOauthAppErrors[keyof PostUserOauthAppErrors];

export type PostUserOauthAppResponses = {
    /**
     * Created
     */
    201: CreateAppResponse;
};

export type PostUserOauthAppResponse = PostUserOauthAppResponses[keyof PostUserOauthAppResponses];

export type DeleteUserOauthAppByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/user/oauth/app/{id}';
};

export type DeleteUserOauthAppByIdErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteUserOauthAppByIdError = DeleteUserOauthAppByIdErrors[keyof DeleteUserOauthAppByIdErrors];

export type DeleteUserOauthAppByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetUserOauthAppByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/user/oauth/app/{id}';
};

export type GetUserOauthAppByIdErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetUserOauthAppByIdError = GetUserOauthAppByIdErrors[keyof GetUserOauthAppByIdErrors];

export type GetUserOauthAppByIdResponses = {
    /**
     * OK
     */
    200: OAuthAppDetailResponse;
};

export type GetUserOauthAppByIdResponse = GetUserOauthAppByIdResponses[keyof GetUserOauthAppByIdResponses];

export type PatchUserOauthAppByIdData = {
    body: PatchAppRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/user/oauth/app/{id}';
};

export type PatchUserOauthAppByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PatchUserOauthAppByIdError = PatchUserOauthAppByIdErrors[keyof PatchUserOauthAppByIdErrors];

export type PatchUserOauthAppByIdResponses = {
    /**
     * OK
     */
    200: OAuthAppResponse;
};

export type PatchUserOauthAppByIdResponse = PatchUserOauthAppByIdResponses[keyof PatchUserOauthAppByIdResponses];

export type PutUserOauthAppByIdData = {
    body: UpdateAppRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/user/oauth/app/{id}';
};

export type PutUserOauthAppByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutUserOauthAppByIdError = PutUserOauthAppByIdErrors[keyof PutUserOauthAppByIdErrors];

export type PutUserOauthAppByIdResponses = {
    /**
     * OK
     */
    200: OAuthAppResponse;
};

export type PutUserOauthAppByIdResponse = PutUserOauthAppByIdResponses[keyof PutUserOauthAppByIdResponses];

export type PostUserOauthAppByIdResetSecretData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/user/oauth/app/{id}/reset-secret';
};

export type PostUserOauthAppByIdResetSecretErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostUserOauthAppByIdResetSecretError = PostUserOauthAppByIdResetSecretErrors[keyof PostUserOauthAppByIdResetSecretErrors];

export type PostUserOauthAppByIdResetSecretResponses = {
    /**
     * OK
     */
    200: NewSecretResponse;
};

export type PostUserOauthAppByIdResetSecretResponse = PostUserOauthAppByIdResetSecretResponses[keyof PostUserOauthAppByIdResetSecretResponses];

export type GetUserOauthAuthorizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/oauth/authorizations';
};

export type GetUserOauthAuthorizationsResponses = {
    /**
     * OK
     */
    200: Array<OAuthConsentResponse>;
};

export type GetUserOauthAuthorizationsResponse = GetUserOauthAuthorizationsResponses[keyof GetUserOauthAuthorizationsResponses];

export type DeleteUserOauthAuthorizationByClientIdData = {
    body?: never;
    path: {
        clientId: string;
    };
    query?: never;
    url: '/user/oauth/authorization/{clientId}';
};

export type DeleteUserOauthAuthorizationByClientIdErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteUserOauthAuthorizationByClientIdError = DeleteUserOauthAuthorizationByClientIdErrors[keyof DeleteUserOauthAuthorizationByClientIdErrors];

export type DeleteUserOauthAuthorizationByClientIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetUserOauthTokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/oauth/tokens';
};

export type GetUserOauthTokensResponses = {
    /**
     * OK
     */
    200: Array<OAuthTokenResponse>;
};

export type GetUserOauthTokensResponse = GetUserOauthTokensResponses[keyof GetUserOauthTokensResponses];

export type DeleteUserOauthTokensByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/user/oauth/tokens/{id}';
};

export type DeleteUserOauthTokensByIdErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteUserOauthTokensByIdError = DeleteUserOauthTokensByIdErrors[keyof DeleteUserOauthTokensByIdErrors];

export type DeleteUserOauthTokensByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetOauthPublicAppInfoData = {
    body?: never;
    path?: never;
    query?: {
        clientId?: string;
    };
    url: '/oauth/public/app-info';
};

export type GetOauthPublicAppInfoErrors = {
    /**
     * Not Found
     */
    404: MessageResponse;
};

export type GetOauthPublicAppInfoError = GetOauthPublicAppInfoErrors[keyof GetOauthPublicAppInfoErrors];

export type GetOauthPublicAppInfoResponses = {
    /**
     * OK
     */
    200: OAuthAppResponse;
};

export type GetOauthPublicAppInfoResponse = GetOauthPublicAppInfoResponses[keyof GetOauthPublicAppInfoResponses];

export type PostAuthWebauthnRegisterOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/webauthn/register/options';
};

export type PostAuthWebauthnRegisterOptionsResponses = {
    /**
     * OK
     */
    200: CredentialCreateOptions;
};

export type PostAuthWebauthnRegisterOptionsResponse = PostAuthWebauthnRegisterOptionsResponses[keyof PostAuthWebauthnRegisterOptionsResponses];

export type PostAuthWebauthnRegisterVerifyData = {
    body: AuthenticatorAttestationRawResponse;
    path?: never;
    query?: never;
    url: '/auth/webauthn/register/verify';
};

export type PostAuthWebauthnRegisterVerifyErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
};

export type PostAuthWebauthnRegisterVerifyError = PostAuthWebauthnRegisterVerifyErrors[keyof PostAuthWebauthnRegisterVerifyErrors];

export type PostAuthWebauthnRegisterVerifyResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAuthWebauthnLoginVerifyData = {
    body: AuthenticatorAssertionRawResponse;
    path?: never;
    query?: {
        isLogin?: boolean;
    };
    url: '/auth/webauthn/login/verify';
};

export type PostAuthWebauthnLoginVerifyErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
};

export type PostAuthWebauthnLoginVerifyError = PostAuthWebauthnLoginVerifyErrors[keyof PostAuthWebauthnLoginVerifyErrors];

export type PostAuthWebauthnLoginVerifyResponses = {
    /**
     * OK
     */
    200: MessageResponse;
};

export type PostAuthWebauthnLoginVerifyResponse = PostAuthWebauthnLoginVerifyResponses[keyof PostAuthWebauthnLoginVerifyResponses];

export type PostAuthWebauthnLoginOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/webauthn/login/options';
};

export type PostAuthWebauthnLoginOptionsResponses = {
    /**
     * OK
     */
    200: AssertionOptions;
};

export type PostAuthWebauthnLoginOptionsResponse = PostAuthWebauthnLoginOptionsResponses[keyof PostAuthWebauthnLoginOptionsResponses];

export type GetAuthWebauthnCredentialsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/webauthn/credentials';
};

export type GetAuthWebauthnCredentialsResponses = {
    /**
     * OK
     */
    200: Array<UserCredential>;
};

export type GetAuthWebauthnCredentialsResponse = GetAuthWebauthnCredentialsResponses[keyof GetAuthWebauthnCredentialsResponses];

export type DeleteAuthWebauthnCredentialsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/auth/webauthn/credentials/{id}';
};

export type DeleteAuthWebauthnCredentialsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutAuthWebauthnCredentialsByIdData = {
    body: CredentialUpdateModel;
    path: {
        id: number;
    };
    query?: never;
    url: '/auth/webauthn/credentials/{id}';
};

export type PutAuthWebauthnCredentialsByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostAuthTwoFactorTotpSetupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/two-factor/totp/setup';
};

export type PostAuthTwoFactorTotpSetupResponses = {
    /**
     * OK
     */
    200: TotpSetupResponse;
};

export type PostAuthTwoFactorTotpSetupResponse = PostAuthTwoFactorTotpSetupResponses[keyof PostAuthTwoFactorTotpSetupResponses];

export type PostAuthTwoFactorTotpEnableData = {
    body: TotpVerifyRequest;
    path?: never;
    query?: never;
    url: '/auth/two-factor/totp/enable';
};

export type PostAuthTwoFactorTotpEnableErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
};

export type PostAuthTwoFactorTotpEnableError = PostAuthTwoFactorTotpEnableErrors[keyof PostAuthTwoFactorTotpEnableErrors];

export type PostAuthTwoFactorTotpEnableResponses = {
    /**
     * OK
     */
    200: MessageResponse;
};

export type PostAuthTwoFactorTotpEnableResponse = PostAuthTwoFactorTotpEnableResponses[keyof PostAuthTwoFactorTotpEnableResponses];

export type PostAuthTwoFactorTotpDisableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/two-factor/totp/disable';
};

export type PostAuthTwoFactorTotpDisableErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
};

export type PostAuthTwoFactorTotpDisableError = PostAuthTwoFactorTotpDisableErrors[keyof PostAuthTwoFactorTotpDisableErrors];

export type PostAuthTwoFactorTotpDisableResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostAuthTwoFactorTotpVerifyData = {
    body: TotpVerifyRequest;
    path?: never;
    query?: never;
    url: '/auth/two-factor/totp/verify';
};

export type PostAuthTwoFactorTotpVerifyErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
};

export type PostAuthTwoFactorTotpVerifyError = PostAuthTwoFactorTotpVerifyErrors[keyof PostAuthTwoFactorTotpVerifyErrors];

export type PostAuthTwoFactorTotpVerifyResponses = {
    /**
     * OK
     */
    200: MessageResponse;
};

export type PostAuthTwoFactorTotpVerifyResponse = PostAuthTwoFactorTotpVerifyResponses[keyof PostAuthTwoFactorTotpVerifyResponses];

export type GetAuthTwoFactorPolicyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/two-factor/policy';
};

export type GetAuthTwoFactorPolicyResponses = {
    /**
     * OK
     */
    200: TwoFactorPolicyResponse;
};

export type GetAuthTwoFactorPolicyResponse = GetAuthTwoFactorPolicyResponses[keyof GetAuthTwoFactorPolicyResponses];

export type PostAuthTwoFactorPolicyEnableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/two-factor/policy/enable';
};

export type PostAuthTwoFactorPolicyEnableErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
};

export type PostAuthTwoFactorPolicyEnableError = PostAuthTwoFactorPolicyEnableErrors[keyof PostAuthTwoFactorPolicyEnableErrors];

export type PostAuthTwoFactorPolicyEnableResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAuthTwoFactorPolicyDisableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/two-factor/policy/disable';
};

export type PostAuthTwoFactorPolicyDisableErrors = {
    /**
     * Bad Request
     */
    400: MessageResponse;
};

export type PostAuthTwoFactorPolicyDisableError = PostAuthTwoFactorPolicyDisableErrors[keyof PostAuthTwoFactorPolicyDisableErrors];

export type PostAuthTwoFactorPolicyDisableResponses = {
    /**
     * OK
     */
    200: MessageResponse;
};

export type PostAuthTwoFactorPolicyDisableResponse = PostAuthTwoFactorPolicyDisableResponses[keyof PostAuthTwoFactorPolicyDisableResponses];

export type GetAdminInvitationsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number | string;
        size?: number | string;
    };
    url: '/admin/invitations';
};

export type GetAdminInvitationsResponses = {
    /**
     * OK
     */
    200: Array<Invite>;
};

export type GetAdminInvitationsResponse = GetAdminInvitationsResponses[keyof GetAdminInvitationsResponses];

export type PostAdminInvitationsData = {
    body: CreateInvitationRequest;
    path?: never;
    query?: never;
    url: '/admin/invitations';
};

export type PostAdminInvitationsResponses = {
    /**
     * Created
     */
    201: Invite;
};

export type PostAdminInvitationsResponse = PostAdminInvitationsResponses[keyof PostAdminInvitationsResponses];

export type DeleteAdminInvitationsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/invitations/{id}';
};

export type DeleteAdminInvitationsByIdErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteAdminInvitationsByIdError = DeleteAdminInvitationsByIdErrors[keyof DeleteAdminInvitationsByIdErrors];

export type DeleteAdminInvitationsByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetAdminInvitationsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/invitations/{id}';
};

export type GetAdminInvitationsByIdResponses = {
    /**
     * OK
     */
    200: Invite;
};

export type GetAdminInvitationsByIdResponse = GetAdminInvitationsByIdResponses[keyof GetAdminInvitationsByIdResponses];

export type PutAdminInvitationsByIdData = {
    body: UpdateInvitationRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/invitations/{id}';
};

export type PutAdminInvitationsByIdErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutAdminInvitationsByIdError = PutAdminInvitationsByIdErrors[keyof PutAdminInvitationsByIdErrors];

export type PutAdminInvitationsByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetAdminInvitationsByIdUsersData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        page?: number | string;
        size?: number | string;
    };
    url: '/admin/invitations/{id}/users';
};

export type GetAdminInvitationsByIdUsersResponses = {
    /**
     * OK
     */
    200: Array<User>;
};

export type GetAdminInvitationsByIdUsersResponse = GetAdminInvitationsByIdUsersResponses[keyof GetAdminInvitationsByIdUsersResponses];

export type GetAdminUsersData = {
    body?: never;
    path?: never;
    query?: {
        page?: number | string;
        size?: number | string;
    };
    url: '/admin/users';
};

export type GetAdminUsersResponses = {
    /**
     * OK
     */
    200: Array<User>;
};

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses];

export type PutAdminUsersByIdStatusData = {
    body: UpdateUserStatusBody;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/users/{id}/status';
};

export type PutAdminUsersByIdStatusErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutAdminUsersByIdStatusError = PutAdminUsersByIdStatusErrors[keyof PutAdminUsersByIdStatusErrors];

export type PutAdminUsersByIdStatusResponses = {
    /**
     * No Content
     */
    204: unknown;
};
